### ISSUE TITLE
Make it easy for people to access the version of guide they need

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#100]
When we make releases of the helm-chart repo, it makes documentation here out of date and no longer accurate for the newest version. However, it *is* accurate for the people who do not upgrade yet. 

So we need to have a way to make it clear to people which version of the helm-chart this guide applies to. This is especially important for the parts of the guide about doing administrative things and what not. Upgrading accidentally from 0.3 to 0.4 when all you wanted to do was change the user image can have catastrophic effects (since you could temporarily lose user's home directories).

How do we make this happen?

RTD allows tagging releases, so we could just tag them here synchronously with releases in the helm-chart repo. Moving these docs into the helm-chart repo is also an option (and might make it easier, so we only have one release process).

We should also make it very obvious to users how to find which version they are running so they can use the docs for the appropriate version.

**Comment by willingc** [comment]
@yuvipanda Nice reframe! I've been doing some thinking about this the past couple of days. I completely agree that we want to look at this from the user's perspective.

I'm going to do a mindmap of all JupyterHub documentation table of contents (probably tomorrow) so we can start iterating on problems and solutions. 

I could see the current JupyterHub documentation morphing into sections for high-level architecture of JupyterHub, component reference, concept reference and glossary, as well as API references. While I could see the ZeroToJupyterHub become the Configuration Tutorial and Administration Guides for JupyterHub when using K8. (It may make good sense for versioning to move this Configuration Tutorial and Administration Guide to the Helm Chart repo, but I want to make sure we understand and agree what we are moving to the helm-chart repo and why).

I would like us to consider moving closer to Kubernetes and OpenStacks (Concept, Task, Tutorial templates and style for documentation) which would enable better versioning of individual pages as well as overall guides.

For our user's benefit, we should have versioning to releases of docs on RTD (it may take the form of providing additional detail in doc footers/sidebar).

I'm in the process of a PR to iterate on the Changelog in the helm-chart repo so that the format is similar to the current changelogs in JupyterHub repos but keeping the cool Cricket stuff too.

**Comment by willingc** [comment]
Meant  to drop the link to the K8 documentation templates here for [reference](https://kubernetes.io/docs/home/contribute/page-templates/).

**Comment by willingc** [comment]
@yuvipanda I'm going to close this since I think we've gotten into a docs groove now.
