### ISSUE TITLE
z2jh not working if NetworkPolicy enabled

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#1044]
With latest z2jh, launched user pod can not communicate with hub when NetworkPolicy is enabled.

This is caused by f20f3e1 [removing the singleuser extraLabel](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/f20f3e16a222b2e6b2bc7de78760e08c76f1593b#diff-96a1791deadeccb98a6f334d195c73a7L207) during the value pass-through change. the `hub.jupyter.org/network-access-hub` label is used as podselector in the network policies installed.

A quick fix would be adding the following the the default values.yaml:
```
singleuser:
  extraLabels:
    hub.jupyter.org/network-access-hub: "true"
```

But this means for installations not enabling NetworkPolicy, the user pods will also have this label, which has no effect but might confuse people looking at pod yaml.  the [original implementation](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/546/files#diff-96a1791deadeccb98a6f334d195c73a7R174) only sets this label when NetworkPolicy is enabled.

**Comment by minrk** [comment]
Good catch! I think the user pods should have this label by default. Would you like to make a PR? It's harmless to have the extra label (it's still useful info), and it will even help enabling the network policy be less disruptive, since it won't force restarting all user pods.

In short: I don't think the presence of the network-policy labels should be affected by whether the network policy is enabled or not.

**Comment by clkao** [comment]
Great! I just checked, both hub and proxy deployments have netpol related labels regardless of the config, so it makes sense for singleuser to do so as well.
