### ISSUE TITLE
Helm install/upgrade fails when podPriority is enabled

### ISSUE THREAD

**Issue by terhorst** [jupyterhub/zero-to-jupyterhub-k8s#1095]
When I run
```
helm upgrade jhub jupyterhub/jupyterhub \
  --namespace jhub  \
  --version 0.8-229848a \
  --values config.yaml
```
I get the error:
```
Fetching cluster endpoint and auth data.
kubeconfig entry generated for jhub.
Error: UPGRADE FAILED: unable to decode "": no kind "PriorityClass" is registered for version "scheduling.k8s.io/v1beta1"
```
(The same thing happened when I used `--install` to install the cluster.)

The `scheduling` portion of my `config.yaml` file looks like:
```
scheduling:
  podPriority: {enabled: true}
  userPlaceholder: {enabled: true, replicas: 0}
  userScheduler: {enabled: true}
```
Everything runs without errors if I disable `podPriority`. 

From Googling this error I found (kubernetes/kubernetes#66900) that it may be related to using a pre-1.11 version of Kubernetes. However, this is not the case for me:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by consideRatio** [comment]
What version of helm are you using? It must be 2.12 or higher I remember, but I don't think that's the issue though...

I always also use `--force` in the `helm upgrade` command, but I expected that to resolve another kind of issue rather than what you see here.

I dislike that its hard to get further information from the helm error message. I think you could resolve this by doing a `helm delete --purge <releasename>` followed by an install, or even a delete of the namespace first as well, but I dislike this kind of measures as it should work without doing such an extreme thing.

I don't understand why though... Hmmmm...

Question: if you do`kubectl get priorityclass --all-namespaces`, does kubectl give you "no such thing as priorityclass" or does it give you "no priorityclasses found"?

**Comment by terhorst** [comment]
Thanks for the quick response. An outdated version of Helm seems to have been the culprit. Updating to Helm 2.12 fixed the error.
