### ISSUE TITLE
Rework idea discussion: simplifying path from config.yaml -> traitlet configuration

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1167]
Perhaps the hardest part for me to follow in the Z2JH codebase is how values provided to `helm` through `config.yaml` end up setting up authentication. There are various reasons for this that I first would like to clarify. After this background, I hope to discuss what we could do to reduce the complexity.

## Background - The complexity of configuring authentication

From provided `config.yaml` values to ending up with a JupyterHub configured to utilize a certain JupyterHub Authenticator class and configuring it, there are multiple steps involved making it hard to track down how to configure `config.yaml` to accomplish the desired result.

The steps from `config.yaml` to a configured JupyterHub Authenticator to be used:
1. A `config.yaml` is made containing something like this:
```yaml
auth:
  type: github
  github:
    clientId: "y0urg1thubc1ient1d"
    clientSecret: "an0ther1ongs3cretstr1ng"
    callbackUrl: "http://<your_jupyterhub_host>/hub/oauth_callback"
    orgWhitelist:
      - "SomeOrgName"
```

2. `helm` is passed values and merges and overrides defaults in the chart's `values.yaml`.

3. The Hub [`configmap.yaml`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/configmap.yaml) and [`secret.yaml`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/hub/secret.yaml) is generated. The ConfigMap will omits some sensitive values while the Secret will pick out some sensitive values.
4. The generated ConfigMap named `hub-config` and Secret named `hub-secret` for the hub is then made available as volumes to the hub pod, and also mounted to the hub container within the hub pod. Note that a ConfigMap or Secret cannot store an actual object declared in YAML syntax, it can only store a string formatted as YAML syntax. This means that each key has simply a string as value.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/jupyterhub/templates/hub/deployment.yaml#L38-L44

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/jupyterhub/templates/hub/deployment.yaml#L96-L100

5. The hub pod is automatically restarted if the ConfigMap or Secret is updated, as it will receive a new annotation with a different hash of the configmap and/or secret if they changed.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/jupyterhub/templates/hub/deployment.yaml#L25-L28

6. The hub will from `jupyterhub_config.py` read the ConfigMap and Secret as files from its filesystem, where each key in the ConfigMap and Secret will become a file. It will also parse the content of these files as yaml. It will do this by relying on functions declared in a file called [`z2jh.py`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/z2jh.py).

7. Some configuration is special in the Secret. Configuration that should be made available as environment variables for the hub pod is exposed under a key/value pair of its own in the Secret.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/jupyterhub/templates/hub/secret.yaml#L8-L18

8. The configuration options read by the `jupyterhub_config.py` through functions declared in [`z2jh.py`](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/z2jh.py) is then utilized to configure [_traitlets_](https://traitlets.readthedocs.io/en/stable/). See [this excellent JupyterCon talk](https://www.youtube.com/watch?v=_gYEVTaNuKU&list=PL055Epbe6d5b572IRmYAHkUgcq3y6K3Ae&index=56) to learn more about traitlets.

9. It is now in this section that I struggle with most. And I hope to reduce this complexity somehow. It becomes complex because it contains a lot of hardcoding, a lot of mixed type of casing, etc...

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/images/hub/jupyterhub_config.py#L244-L340

## On what we can do to improve

- Perhaps we can configure the traitlets for authentication in `jupyterhub_config.py` more generic way, thereby reducing complexity and supporting additional configuration options by the authenticator classes without needing to update the chart.
- Perhaps we could utilize a single secret instead of both a configmap and a secret?
- Perhaps in the authentication configuration, we could support the old usage of `clientId` and other fields written with camelCase while also supporting `client_id` written in snake_case?
- Fix the bugs I think I've spotted.

### Using `None` values

I think we end up using `None` values by always doing the last two lines of this snippet for various authenticators.

__Google's authenticator is ok__
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/images/hub/jupyterhub_config.py#L254-L263

__But cilogin, gitlab, mediawiki and globos isn't correctly configured I think__

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/100da29e2656676586ddcd895df31dea5f4aa147/images/hub/jupyterhub_config.py#L280-L285

- [x] google
- [x] github
- [x] cilogin
- [x] gitlab
- [x] mediawiki
- [x] globus
- [x] hmac
- [x] dummy
- [x] tmp
- [x] lti
- [x] ldap
- [x] custom

**Comment by minrk** [comment]
>  Perhaps we can configure the traitlets for authentication in `jupyterhub_config.py` more generic way, thereby reducing complexity and supporting additional configuration options by the authenticator classes without needing to update the chart

it would definitely be simpler *for us* to expose the underlying configuration structure more directly, rather than defining our own configuration structure and them mapping that onto the underlying structure (e.g. transform `auth.whitelist.users` to `Authenticator.whitelist`). However, I'm not sure if it's simpler for users who don't know about the underlying structure. Seeing `snake_case` in the middle of a `camelCase` block might be confusing since it's not clear when the transition from helm config to underlying Authenticator config is happening.

>  Perhaps in the authentication configuration, we could support the old usage of `clientId` and other fields written with camelCase while also supporting `client_id` written in snake_case

We do automatically convert `snake_case` to `camelCase` in jupyterhub_config.py since most configuration values do map through a simple transform. We could just as easily do the reverse to ensure that any `auth.mediawiki.configValue` sets `MWOAuthenticator.config_value`. That would let the config values be simple passthrough (only map mediawiki -> MWOAuthenticator).

The 0.8 chart did greatly simplify things because to expose a new option, we know that all of values.yaml is passed through to the image as values.yaml (the configmap/secret split is re-merged so that is a hidden implementation detail from both users and jupyterhub_config.py). We at least no longer need to deal with the configmap having its own structure distinct from both.

>  Perhaps we could utilize a single secret instead of both a configmap and a secret

I thought we couldn't use secrets because they have a small maximum size, but apparently so do configmaps and they both appear to be 1MB, so maybe we can do this.

>  I think we end up using `None` values by always doing the last two lines of this snippet for various authenticators.

Yup, that's definitely missing the `if None:` block from the other sections. Should be an easy fix since it's the same line in all the other sections.

**Comment by consideRatio** [comment]
I'm closing this issue, but its still referenced as a reminder of the struggles of authenticator configuration from the issue triage report.
