### ISSUE TITLE
PodDisruptionBudget errors with helm upgrade

### ISSUE THREAD

**Issue by rokroskar** [jupyterhub/zero-to-jupyterhub-k8s#1282]
helm chart version: 0.9-e120fda

A recent `helm upgrade` left me with a few `no PodDisruptionBudget found` errors. First:

```
Error: no PodDisruptionBudget with the name "user-placeholder" found
```

as reported already in #1235. We don't actually want those `user-placeholder` pods so setting `scheduling.userPlaceholder.enabled=false` solved the issue. However, 

```
Error: no PodDisruptionBudget with the name "user-scheduler" found
```
was more puzzling. I didn't enable the `user-scheduler` so I was surprised to hear about a pdb being created for it.  I see that I have to set not only `scheduling.userScheduler.enabled=false` but also `scheduling.userScheduler.pdb.enabled=false` (see [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/scheduling/user-scheduler/pdb.yaml#L1)). 

Is this intended? If not, I can send a PR with a fix.

**Comment by consideRatio** [comment]
Thank you @rokroskar this is very valuable input!

I really don't get what is going on with Helm in general regarding these... PDBs are very troublesome for Helm as they need to be recreated instead of modified when changes are made, and I've seen these kinds of upgrade issues many times without really grasping what helm's issue is.

I know that adding the flag `--force` can be of relevance, as it forcefully recreates the PDBs if changes are made.

Perhaps something that could have happened that somehow triggered this behavior, which I don't find acceptable, is that first a PDB was created because at some point it was enabled. Then later this PDB was never removed, or it was, and Helm is struggling with maintaining the state of this resource somehow.

I'm open to fixes to this issue, but I don't see... OH!!!!!! ;D Now I see what you meant! YES! :D I'd love to see a PR fix where you add the condition that `scheduling.userScheduler.pdb.enabled=true` as well.

**Comment by consideRatio** [comment]
Wieeee! I'm really excited about this being corrected! NICE CATCH!

**Comment by rokroskar** [comment]
Hi @consideRatio, that will fix the second of the two problems I encountered, but the first one remains. I didn't disable the `userPlaceholder` initially so it should not have failed. The `pdb` was there, but maybe the problem is more subtle as you say. I don't feel comfortable resorting to `--force` if not really necessary since Jupyterhub is just one one of the several dependencies of our deployment. I don't have much experience with `pdb`s, perhaps this is a generic problem?

**Comment by consideRatio** [comment]
@rokroskar yes I think PDBs + Helm have issues in general for some reason, but whenever you end up with things that needs to be deleted in order to be updated, `--force` is the option required with helm =/

But, simply deleting something or creating something in the first place should be fine without `--force` i think.

Hmmm okay so the first issue... Ill inspect things more and try to make sure it is not related to our chart.

**Comment by consideRatio** [comment]
What version of Helm are you using?

**Comment by consideRatio** [comment]
Related: https://github.com/helm/helm/issues/2914

I don't see an issue with our kubernetes resources, I currently assume Helm is messing with us. Why is not obvious and perhaps we can avoid triggering helm to mess with us.

**Comment by rokroskar** [comment]
yes it's entirely possible it's a Helm problem. Mine:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Comment by rokroskar** [comment]
btw, looking at the chart, is there a case where you don't want the PDB to be created if you create the `user-scheduler`? You could always make it to have zero replicas by default (as is the case with the `user-placeholder`. It's not a big deal to extend the logic but the behavior between the two components will be different and maybe confusing.

**Comment by consideRatio** [comment]
Ah yes the user-scheduler Deployment could certainly always be created by default with 0 replicas. But I guess the enabled / disabled part information in the configuration needs to be provided anyhow and if it was disabled we would need that to override the replicas to go down to zero which seems a bit more complicated.

I'm a bit confused about what you meant, we have the user-schedulers deployment, and the user-schedulers PDB. We also have the user-placeholders statefulset and the user-placeholders PDB.

- The user-placeholders PDB should always be maximally permissive with `minAvailable: 0`, and this is currently not configurable due to this assumption.
- I'm not a fan of the asymmetry we have regarding having an pdb enabled flag for user-scheduler but not for user-placeholder, but at the same time we should always have one if we have a user-placeholder statefulset / deployment.
- Adding configuration options comes with the downside of indicating it could make sense to configure something, even though it could be confusing that you cant as well.

I currently don't have a clear mind of a change that I think should be done regarding anything else, but I'm very flexible in my mind regarding the question of making changes here - I really don't want the chart to cause errors like these for some reason.
