### ISSUE TITLE
How does image-awaiter and image-puller interact?

### ISSUE THREAD

**Issue by Lastcysa** [jupyterhub/zero-to-jupyterhub-k8s#1305]
Hi,

I am very interested in your idea of pulling necessary images on all k8s cluster nodes in advance to reduce start-up time. I just wanted to fully understand your implementation of this idea. I found two directories in the repo related to this, namely `image-puller` (all yaml files) and `image-awaiter` (go and Dockerfile). However after some investigation into the docs and codes I still could not figure out how they interact with each other to get this done. It seems like in `image-awaiter` it simply gets a DeamonSet running and checks if the image has been present on all nodes - but where is the actual image-pulling procedure implemented? Also, How does it talk to the k8s cluster since no Kubernetes api is called?

I may be asking silly questions, but any guide or hint will be very much appreciated. Thanks!

**Comment by consideRatio** [comment]
Ill write more in length later, but in short, an k8s api is actually called. The image awaiter will inspect the Daemonset status and when all of them are in ready state the initcontainers of the puller pods from the puller Daemonset has then finished.

This is done in the image of the image-awaiter, a go binary that does checks to the k8s api using provided RBAC permission to do so

/ erik from mobile in a hurry

**Comment by consideRatio** [comment]
[This section in the guide](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html#pulling-images-before-users-arrive) describes usage of the image-pullers, but indeed, it does not describe the hook-image-awaiter and the hook-image-puller's interaction.

I think as a way to close this issue, we can add a note on that page or perhaps a page specifically to give insight into various components like this. I think the latter could be useful, next to overview of networking and such.

## How the hook image pulling works

When `helm upgrade` is run, it will start by rendering the Helm chart's templates using the provided values, after which it will register the resources annotated as [_Helm hooks_](https://helm.sh/docs/topics/charts_hooks/) with the k8s api-server, like `"helm.sh/hook": pre-install,pre-upgrade` for example. Then, it will wait for these resources, and then it will continue with its installation.

When `prePuller.hook.enabled=true`, we install two Helm hook resources pre-install,pre-upgrade. One Job resource that creates a Pod until it runs to completion, and one DaemonSet. The Job, which pod you will recognize as `hook-image-awaiter-*` is a simple image with a single Go binary executable whose purpose is to ask the k8s api-server about the state of the associated Daemonset, the other Helm hook resource we install. A DaemonSet will create pods on each node it is allowed to schedule a pod on, and these pods are very silly. They have X number of `initContainers` that only exits directly on startup, this is because their purpose is simply to force the node where the pod run to download the image. The Pod's single normal container is just a dummy container that does nothing (`k8s.gcr.io/pause`).

Now the hook-image-awaiter will simply ask the k8s-apiserver, repeatedly about the status of the hook-image-puller DaemonSet, which will report that it has X number of scheduled pods, Y number of desired pods, and Z number of running and ready pods. The logic of the hook-image-awaiter is then just to compare the number of pods that are desired with the number of pods running, and exit when they match.

Recently, we realized that sometimes the hook-image-puller pods may fail to schedule because of a hard limit of the number of pods in a k8s node for example, which could make the entire `helm upgrade` command get stuck. To avoid this, we updated the logic in #1763 and #1787 to let the `hook-image-awaiter` relax and start comparing only the successfully scheduled pods with the ready pods, instead of the desired number of scheduled pods with the number of ready pods.

**Comment by consideRatio** [comment]
Closing as stale and perhaps a bit out of scope to document as part of the z2jh.jupyter.org guide, but maybe?
