### ISSUE TITLE
Describe singleuser dependency on jupyterhub

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#135]
On a recent deployment, the version of jupyterhub inside the singleuser image did not match that of the hub itself. The single user image wasn't able to spawn until I synced the version inside single user image with that of the hub.

**Comment by willingc** [comment]
@ryanlovett Some of the recent (< 1 week) made by @minrk to JupyterHub should help avoid this. Likely worth mentioning in the doc too.

**Comment by minrk** [comment]
We've traded one kind of sensitivity for another: We make very few assumptions about the container now (it has jupyterhub-singleuser is about it), but one strong requirement: that jupyterhub-singleuser version matches that of the Hub.

**Comment by choldgraf** [comment]
I think @yuvipanda mentioned that this could be addressed by instruction people to set their jupyterhub version to an environment variable e.g. `JUPYTERHUB_LATEST` or something like that...this means that the hub version could be updated and people wouldn't need to change their dockerfiles when versions changed

**Comment by yuvipanda** [comment]
Nope, that is only for binder, not z2jh

**Comment by minrk** [comment]
https://github.com/jupyterhub/jupyterhub/pull/1368 provides a pretty loud, informative error when login fails due to the version mismatch. I presume the helm chart should specify a version of jupyterhub without flexibility. If that's the case, what's probably in scope for z2jh is:

1. make it clear what version of jupyterhub a given version of the chart provides
2. how to ensure that the correct version of jupyterhub is installed in your user image (~always `RUN python3 -m pip install jupyterhub==<version>` to your Dockerfile).

It would probably be difficult to enable varying the jupyterhub version in the helm chart safely.

We could have a test, though, to verify the version by running `jupyterhub-singleuser --version` in the chosen image. Is it possible to run a test like that as part of preflight checks?

**Comment by consideRatio** [comment]
We are currently herding the users to utilize images from jupyter/docker-stacks that comes with jupyterhub already.

If we add this documentation details, it may be in a very advanced section that also needs to mention what userId etc to configure. I'm trying to triage a lot of stale issues, I'll close this for now, feel free to reopen.
