### ISSUE TITLE
Download multiple files from notebook server?

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/zero-to-jupyterhub-k8s#1352]
The question is quite simple, I want to know if it is possible to allow for multi select of files in a notebook server and download them all? My use case is that a user is exporting a lot of data, too much for one single file. There will be 100+ files. 

To download the 100+ files, they will need to select each of them individually and press download. This is because the download button is disabled when you select more than 1 file

With 1 file selected:
![Screen Shot 2019-08-08 at 10 34 57 AM](https://user-images.githubusercontent.com/3789407/62724730-7a6be580-b9c8-11e9-88f1-deafb9e73528.png)

With >1 file selected, **_download button is gone_**:

![Screen Shot 2019-08-08 at 10 35 16 AM](https://user-images.githubusercontent.com/3789407/62724728-78098b80-b9c8-11e9-8a8f-364e9aa8bd1f.png)

**Comment by betatim** [comment]
Hi there 👋!

You also posted this question in https://discourse.jupyter.org/t/download-multiple-files-from-notebook-server/1863. We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to the forum so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

I'll close this here as the forum is the right place to discuss this
