### ISSUE TITLE
Create an appendix with general status info for each major cloud provider

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#1362]
Many times, the decision to use one cloud provider or not is a product of JupyterHub per-se, but the state of features that JupyterHub uses on that particular cloud provider. E.g., the state of Kubernetes-as-a-service and reliability in scaling up/down nodes.

Would it be valuable it we kept an appendix page for each major provider that had a sort of "this is the community's latest experience with this provider" page, including any "gotchas" that people ran into while running on that provider?

It might help users figure out where they want to try deploying their hubs, and a way to avoid issues that aren't hub-specific but instead provider-specific...

**Comment by choldgraf** [comment]
cc @trallard who thought this might be a cool idea!

**Comment by consideRatio** [comment]
@choldgraf I agree this could be useful, but it could be a bit troublesome to maintain. I think I'd like it to be quite objective if we had one, so it's easier to say "true" or "false" during reviews, rather than maintaining an opinion which seemingly is representing the repository or project jupyter, which may actually be the opinion of a contributor with experience of the cloud provider.

Hmmm, I'd like to close this issue as it wasn't picked up for a year and I don't feel like it at picking it up myself. Let me know what you think Chris!

**Comment by choldgraf** [comment]
Yep I'm +1 on closing it. I think the information would be super helpful, but it's not realistic that we'd be able to keep it up-to-date. Instead perhaps we can encourage people to write up their experiences / updates / etc in the community forum

**Comment by consideRatio** [comment]
@choldgraf or have a google forms poll form, or some poll or similarly, hmm...

**Comment by choldgraf** [comment]
An annual user survey would be really cool
