### ISSUE TITLE
Can oauth flow between single user pod and hub be disabled?

### ISSUE THREAD

**Issue by ajaysurapaneni** [jupyterhub/zero-to-jupyterhub-k8s#1377]
We have an external authenticator which does the authentication and provides a bearer token and this is used for logging into jupyterhub. On the jupyterhub, we are using jwtauthenticator that decodes the received token to identify the username. The identified user is allowed to spawn the single user pod and till this point all is working as expected. 

The problem is we have issue in maintaining the session state in browser. As the single user pod also triggers an Oauth flow with hub to get his token, the request to generate token from userpod comes with a different session_state  which doesn't match with the actual one. Is there a way that we can completely disable the oauth flow that is happening between single user and hub. We don't require this oauth flow as we are already authenticating the user even before he logs into the hub.

And can some kindly explain why this oauth flow is required between userpod and hub ?

**Comment by minrk** [comment]
> Is there a way that we can completely disable the oauth flow that is happening between single user and hub.

The `jupyterhub-singleuser` entrypoint could be modifies to change the `.get_user()` [method](https://github.com/jupyterhub/jupyterhub/blob/917786f2f5abdd5163770949c04f507ea0c23d84/jupyterhub/singleuser.py#L99-L108) to check your jwt token instead of beginning the JupyterHub auth process.

> And can some kindly explain why this oauth flow is required between userpod and hub ?

It is because auth cookies are not shared from the Hub to user servers. If they were, it would be trivial for users to steal each others' credentials with a link to their own server since auth is implemented in the user servers rather than in the proxy. Since cookies are not shared, we need a mechanism to communicate authentication from the Hub to the single-user server. In JupyterHub, that's OAuth. Without it, we would not be able to identify who a user is when they visit the single-user server.

**Comment by ajaysurapaneni** [comment]
Thanks Min. Will check the behavior and let you know my observations.

**Comment by suryag10** [comment]
Hi Min,
If we use an external authenticator service and receive JWT as part of the authentication, can we reuse the same in this flow?.  we tried to use the https://pypi.org/project/jupyterhub-jwtauthenticator/, but we are getting erros in the user to jhub OAuth flow.

**Comment by consideRatio** [comment]
At this point in time, this issue is to vague to followup concretely with something that influence the content of this repo, so I'll go ahead and close it.
