### ISSUE TITLE
Single-user server warning (question)

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1390]
I have just noticed the following warning in a single-user server log output:

```
[W 2019-09-06 12:58:45.288 SingleUserNotebookApp _version:50] jupyterhub version 1.0.0 != jupyterhub-singleuser version 0.9.2. This could cause failure to authenticate and result in redirect loops!
```

I'm wondering about root cause for this issue, potential adverse effects and corresponding fixes. In this particular instance, the server has launched fine, but ...

**Comment by chicocvenancio** [comment]
it just means the singleuser image you're using expects a different version of jupyterhub than the hub has, and vice-versa. Though it is most often compatible it may present a problem, as the warning states.

**Comment by ablekh** [comment]
@chicocvenancio Thank you. I understand what the message says. What I don't understand is 1) why this happens (because Z2JH is supposed to be consistent about components used and their versions) and 2) how to (optimally) fix this.

**Comment by manics** [comment]
It's probably just that the singleuser sample hasn't been updated since 2018 https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commits/master/images/singleuser-sample/Dockerfile

Presumably if you're using an up-to-date https://github.com/jupyter/docker-stacks base-image you won't see the warning?
