### ISSUE TITLE
PR Discussion - chartpress to not rebuild all the time

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1403]
As @clkao has realized and pointed out, chartpress is rebuilding all the used images all the time during testing. I'm right now looking at a build job (https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/jobs/583123527) where no image has been changed, but they are all being rebuilt. Sometimes the Travis workers are relatively busy and this end up taking even than 20 minutes to complete.

While there is multiple improvement possibilities, an essential one I think is to not rebuild all the time.

---

This was a duplicated issue of this: https://github.com/jupyterhub/chartpress/issues/40

**Comment by betatim** [comment]
Maybe we can have travis pull the latest image from docker hub and then rebuild with `--cache-from` which should result in a no-op if nothing has changed but if something is new it'll be rebuilt.

**Comment by consideRatio** [comment]
Good suggestion, perhaps making a monthly full rebuild or similar, hmmm... @clkao what do you think?

**Comment by clkao** [comment]
The root cause was the remote docker repo tag probing, which does not work when docker mirror is configured, as in travis-ci environment.

a workaround is the disable such config in docker-daemon.json as in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1259/files#diff-6a7df502b04014cd6ba348f1e274d21c
