### ISSUE TITLE
Error of Node Auto-provisioning on JupyterHub GCE 

### ISSUE THREAD

**Issue by Felihong** [jupyterhub/zero-to-jupyterhub-k8s#1439]
Hello Everyone,

We have successfully deployed the Jupyter Hub on GCP Kubernetes Engine and also have setup the cluster autoscaler which takes care of node autoscaling. 
We now want to enable the Node Auto-Provisioning for allocating the ressources, but based on the below configuration to enable node auto-provisioning we get the errors when spawning a server:

```
gcloud container clusters create $CLUSTER_NAME --zone=$ZONE \
    --machine-type=$SYSTEM_MACHINE_TYPE --no-enable-legacy-authorization \
    --enable-autoscaling --max-nodes=$MAX_SYS_NODES --min-nodes=$MIN_SYS_NODES \
    --scopes=$SCOPES 

gcloud beta container clusters update $CLUSTER_NAME --zone=$ZONE \
  --enable-autoprovisioning \
  --min-cpu 1 \
  --max-cpu 20 \
  --min-memory 1 \
  --max-memory 128 \
  --max-accelerator type=nvidia-tesla-k80,count=4
```

<img width="780" alt="error" src="https://user-images.githubusercontent.com/28823328/66381195-22962e80-e9b9-11e9-96f8-ebad4cd52184.png">

Any ideas why?

**Comment by consideRatio** [comment]
I'm not sure how the GKE node-autoprovisioning works and/or how it interacts with the cluster-autoscaler, which I believe is the k8s mechanism to trigger request of additional nodes when pods are pending.

It is a bit out of scope to try help you resolve this because this is to debug a lot about google's node autoprovisioner specifically, and I lack experience on it personally. Please feel free to open a question about this in the discourse.jupyter.org forum!

Thank you for providing a clear background to your issue @Felihong !
