### ISSUE TITLE
jupyterhub can not start

### ISSUE THREAD

**Issue by rolinston4** [jupyterhub/zero-to-jupyterhub-k8s#1469]
![image](https://user-images.githubusercontent.com/28034434/68098218-70d61900-fef6-11e9-8343-a4d88aa72c73.png)
Why this happen

**Comment by consideRatio** [comment]
I don't know =/

I also know too little in order to try help. I think it may relate to a change you have done following https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1458.

I don't know for sure why you got the issue in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1458, but missing environment variables like those ending with SERVICE_HOST seems to me like a good indication of Kubernetes was setup with some issues or something.

---

It is simply too hard for me or others to help you with this limited information I think. To properly resolve this, you need to describe:
- how your kubernetes was setup to some extent, was it manually on your own servers or using GKE / AKS etc for example
- what kubernetes version did you setup?
- what helm version did you use?
- what jupyterhub chart version did you install?
- what additional values did you provide helm? (content of config.yaml)
