### ISSUE TITLE
Document new features added in 0.8

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#151]
It seems like a bunch of nifty new features have been added in 0.8...do we have a changelog somewhere so that I can take a stab at mentioning them in z2jh?

In particular, it seems that https://github.com/jupyterhub/jupyterhub/pull/1243 makes it possible to run multiple docker images with a single jupyterhub. If so, that's something that almost everybody asks for so we should make sure that it's well-exposed to users :-)

**Comment by willingc** [comment]
The changelog is available in the JupyterHub docs. There's also a link in the docs that does a full delta between 0.7.2 and 0.8 beta.

**Comment by choldgraf** [comment]
Thanks! Are all of these additions documented in the docs as well? It sounds like maybe this has already been done? If not perhaps we can have a team pow-wow to discuss what kinds of things to highlight from a user perspective (e.g., for a blog post, documentation, etc)

**Comment by willingc** [comment]
The latest JupyterHub documentation reflects the additions/changes for 0.8. This was done before 0.8 went into beta. There may be things that surface during beta that we will continue to refine or add to the JupyterHub docs.

Typically, @minrk writes a blog post for each release of JupyterHub and we pitch in on edits. I'm assuming that when 0.8 moves to RC that will be the time when the blog post will begin getting drafted.

I'm assuming that this issue is to cover what to add to the Zero to JupyterHub docs that a user may find helpful. 

It makes sense to have a discussion with all of us (you, me, @yuvipanda, and @minrk) to discuss what makes sense for a Kubernetes deployment and a user's ability to have multiple servers (or images) and outline what to document here in Zero to JupyterHub.

**Comment by ryanlovett** [comment]
Chris, re:

> In particular, it seems that jupyterhub/jupyterhub#1243 makes it possible to run multiple docker images with a single jupyterhub. If so, that's something that almost everybody asks for so we should make sure that it's well-exposed to users :-)

It has been possible for a user to choose from among multiple docker images within a single jupyterhub, but it hasn't been possible for one user to run two servers (dockerized or not) simultaneously. That feature is in 0.8, but there's no UI for it yet. I believe that will come with 0.9.

**Comment by choldgraf** [comment]
@ryanlovett do you know where it's documented how to set up a jupyterhub so that this works:

> It has been possible for a user to choose from among multiple docker images within a single jupyterhub

?

I'd love to add this to z2jh...people always ask me how to do this

**Comment by ryanlovett** [comment]
Yes, in a run-of-the-mill hub you can use [imagespawner](https://github.com/ryanlovett/imagespawner) or something similar. You'd have to do more plumbing to integrate the same functionality into z2jh. Binderhub appears to pass the image from the authenticator to the spawner to singleuser_image_spec (see values.yaml). No doubt @yuvipanda already knows how the regular hub will do this. :)

**Comment by yuvipanda** [comment]
We did and released it as part of v0.5!
