### ISSUE TITLE
Add Helm chart to Artifact Hub (Helm Hub's new home)

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1517]
With Helm 3 there's a push towards decentralised chart repos: https://github.com/helm/hub/blob/master/README.md
The old https://github.com/helm/charts/ repo is being deprecated

Helm 3 includes a command for search Helm Hub:
```
$ helm search hub jupyterhub
URL                                             CHART VERSION   APP VERSION    DESCRIPTION                    
https://hub.helm.sh/charts/cern/jupyterhub      0.9-dev         1.0.0          Multi-user Jupyter installation
```
And you can also search on https://hub.helm.sh/

Should we try and get https://jupyterhub.github.io/helm-chart/ added? The process and requirements for getting a repo listed is in https://github.com/helm/hub/blob/master/Repositories.md

**Comment by consideRatio** [comment]
Closed #1065 in favor of this, this is still relevant but may require some work to be conformant. For example, I'm quite confident we need #1017 to be resolved first, and I'd like to do that in a sensible way.

**Comment by manics** [comment]
Do you have a link to the guide suggesting #1017 is required?

**Comment by consideRatio** [comment]
## Requirements from [Helm hub docs](https://github.com/helm/hub/blob/master/Repositories.md)

- [ ] Every chart to have a maintainer listed along with valid contact information for each maintainer. The contact information could be in the form of an email address or link to a contact form
- [x] Charts to pass Helm lint, be installable and upgradable in all community supported versions of Kubernetes, and to use semantic versioning to share intent in released changes. To help with this we suggest leveraging the Chart Testing project.
  - [x] Charts to pass Helm lint (part of our CI system)
  - [x] be installable and upgradable in all community supported versions of Kubernetes (~1 year / ~3 minor versions, so 1.19, 1.18, 1.17 atm).
  - [x] and to use semantic versioning to share intent in released changes
- [x] Have a NOTES.txt template with useful information which Helm will display after installation
- [x] Chart versions to be immutable

## Migration to Artifacts Hub
Apparently Helm hub is deprecated and being migrated to Artifacts hub, so our process should be to register with them! See [these docs](https://github.com/helm/hub/blob/master/README.md#claiming-your-repo-in-the-artifact-hub).

- [ ] If you create an account on the Artifact Hub there is a method to claim your repository. In the repository settings you will find a button to start the process. Note, the Artifact Hub has both user and organizational accounts. If you have an organization, consider linking the repository to the organization instead of an individual user.

We should register the jupyterhub github org!

From the [Artificats hub docs](https://github.com/artifacthub/hub/blob/master/docs/repositories.md#ownership-claim) about ownership claims:

> Any user is free to add any repository they wish to Artifact Hub. In some situations, legit owners may want to claim its ownership to publish it themselves. This process can be easily done in an automated way from the Artifact Hub control panel.
>
>First, an artifacthub-repo.yml metadata file must be added to the repository you want to claim the ownership for. The user requesting the ownership must appear in the list of owners in the metadata file, and the email listed must match with the one used to sign in in Artifact Hub. This information will be used during the process to verify that the requesting user actually owns the repository.
>
>Once the repository metadata file has been set up, you can proceed from the Artifact Hub control panel. In the repositories tab, click on Claim Ownership. You'll need to enter the repository you'd like to claim the ownership for, as well as the destination entity, which can be the user performing the request or an organization. If the metadata file was setup correctly, the process should complete successfully.

**Comment by consideRatio** [comment]
Closed by https://github.com/jupyterhub/helm-chart/pull/114 and subsequent correctional PRs
