### ISSUE TITLE
Extension to zip/download the current directory

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#152]
@fcollman brought up a good point about the Binder/JupyterHub teaching approach, which is that right now it's a bit unclear how people should (or could) get their material *off* of the cloud computing and into a state that they personally have more control over. 

Right now it sounds like the best way to do this is with a jupyter extension that zips the current directory and then downloads it. PRs to this effect are welcome :-)

Old thoughts
---
This could be some combination of:

1. Easily download all of their notebooks / materials in their jhub
2. Easily clone the current state of their material onto their own github account
3. Push the docker image served through their `singleuser` image to a public registry (or one that they have control over)

Or more generally, tips for what to do *after* jupyterhub to ensure people keep using the tools. I think this could be addressed either with new tech or with better documentation...probably in the short-term documentation is the way to go.

What do folks think about this? Any other ideas to add to the list of 3 items above?

**Comment by yuvipanda** [comment]
Can you explain more what (3) means? I don't quite understand it. 

(2) is beyond the scope of this guide IMO - it entails we have enough documentation on git, authenticating to github, creating ssh keys and pushing. Creating ssh keys inside a jupyterhub environment is also a big security risk, since anyone with access to those keys can fully access your entire account.

Having a simple extension that lets you download a directory as a zip file / tar file seems like the thing we can do here. So someone would have to write that extension, and then we'd have to point to it from here :)

**Comment by choldgraf** [comment]
yep, I think that is fine w/ me too...agree w/r/t supporting a buncha extra stuff we don't want to support.

**Comment by choldgraf** [comment]
I'm gonna change the topic of this issue to reflect this

**Comment by fcollman** [comment]
I think the idea behind 3 was to allow people to capture a frozen version of their working docker image that they were operating with. The binder mechanism doesn't really GAURUNTEE that a certain docker image will be available at some time in the future. So this discussion was based around wanting to give people access to that snapshot in time and let them bring that snapshot out of the current binder deployment, because  I think binder doesn't want to be making any gauruntees that it won't purge it's docker image cache at any point. Or put another way binder doesn't want to be docker hub, but people developing notebooks and students who make them do want a way to have gaurunteed reproducibility.

**Comment by choldgraf** [comment]
Yeah - I think that true reproducibility is going to be a combination of tech + guidelines development. For now, just being able to zip your files up and put 'em on your computer is an inelegant but useful first step. For things like re-using the Docker images used in jupyterhub...I'm not sure the best solution.

@yuvipanda - is Docker running on the user pods themselves? Is this something that somebody could one day turn into a jupyter extension? (trying to figure out if the pieces are in place to recommend people give a shot at a solution since I don't think we have the bandwidth to do this right now)

**Comment by yuvipanda** [comment]
No, users never get access to docker directly, since access to docker pretty much gives them root over the entire cluster. We take some steps to make sure they don't get access to docker directly, in fact.

I think the workflow for keeping your own docker image of a repository is for us to document how to do that with repo2docker - it was split up for this reason. So we can have a 'if you want your own docker image that is built just like this, here is how'. I don't think we can do that from binder itself - users will have to install and do it locally.

**Comment by choldgraf** [comment]
Yeah - at the bootcamps I've taught, people usually say something to the effect of

"ok, so how do I literally take everything I have on the cluster (environment, data, analysis, etc) and move it to someplace else since the jupyterhub will be spun down after the bootcamp".

So right now our solution for this would be:

1a. Use Docker on your own machine (or wherever you're doing your work) to grab the Docker image for this bootcamp.
or
1b. Use `repo2docker` in the same way that it was used to build the course Docker image.
2. Zip -> download -> copy/paste all of your files into this new docker image.

?

**Comment by choldgraf** [comment]
(fwiw I'm less concerned about this for Binder...I think that the binder experience is short-term enough that we can just tell people how to re-create the same docker image and that's enough. But for JupyterHubs used in a class/bootcamp/etc, there has probably been a lot of development done on the jhub that goes beyond the initial docker image)

**Comment by willingc** [comment]
I recommend closing this issue here as out of scope for this guide. It seems to be better suited as either a binder enhancement or jupyterhub enhancement issue.

**Comment by choldgraf** [comment]
How about I change the topic so that it's more documentation-related? I think that whenever we do have some kind of best-practices, we should mention it in the z2jh guide (similar to the short section on reproducibility). I can open up an issue in jupyterhub about the tech development. WDYT?

**Comment by willingc** [comment]
In general, I prefer issues that are well scoped and are actionable vs without a concrete next step.

If there is technical development work to be done, then the issue should go somewhere else. If new development is not needed and the next action is to explain how to export/download workshop configuration and files, then we should leave it here.

It's a bit unclear (vague) to me what information the user wishes to extract from the workshop. Perhaps we leave it open here for now, and we clarify exactly what config/information is needed.

cc/@minrk Thoughts?

**Comment by choldgraf** [comment]
Yeah, I'm thinking we could:

1. Change the title of this to "instructions for migrating files off of JupyterHub". Then open a PR here that simple gives the shell commands to `tar` everything and download it via the Jupyter interface (that's what we've done in bootcamps I've attended). That PR would close this issue.

2. Open an issue in jupyterhub that discusses the idea of doing the above with a button of some kind.

WDYT?

**Comment by willingc** [comment]
Excellent. Let's do 1 for now and see how that goes before opening 2. Thanks @choldgraf.

**Comment by choldgraf** [comment]
(will get to this in the next few days...traveling to london right now!)

**Comment by yuvipanda** [comment]
+1 on the approach. I've @SaladRaider on writing an extension to do the downloading.

**Comment by choldgraf** [comment]
I hear rumors that this has been done? @yuvipanda ?

**Comment by yuvipanda** [comment]
This is done. Not sure where / how we should link to it though.

**Comment by choldgraf** [comment]
@yuvipanda is there a plan to cut a release sometime soon? Once it's on `pip` then we should definitely add to the z2jh documentation.

That said, at some point we should have a different set of documentation that is more "practice-focused" rather than setting up the jupyterhub itself. E.g., that'd be a place where we could discuss nbgitpuller, nbzip, etc. This feels to me like more of a separate resource than Z2JH, hopefully that could be community-maintained by practitioners. What do you think?
