### ISSUE TITLE
Broken docs cross-links

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1601]
I'm pretty sure these Sphinx cross-references used to work before, was I just imagining it?

- https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-helm.html
  - `preliminary instructions are available for testing.` link to `<setup-helm3>` is broken
  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/7b4a873b6795ffb5d986ca7f713e4ee635c4600f/doc/source/setup-jupyterhub/setup-helm.rst#L29

- https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-jupyterhub.html
  - `Now that we have a Kubernetes cluster and Helm setup` links to `<create-k8s-cluster>` and `<setup-helm>` are broken
  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/7b4a873b6795ffb5d986ca7f713e4ee635c4600f/doc/source/setup-jupyterhub/setup-jupyterhub.rst#L6-L7

**Comment by betatim** [comment]
Are these cross-references internal to the docs or to other sphinx documentation?

Maybe they are broken because the pydata-docs-theme doesn't support them? @choldgraf

**Comment by choldgraf** [comment]
I don't think so, more likely the pages just moved. the `doc` role needs a relative path to an actual file, and I don't see a `create-k8s-cluster` file in the `setup-jupyterhub` folder, so I think this will be fixed by hunting down the proper pages and updating the links.

As an aside: another way we could catch this is to make our docs build use the sphinx "strict" mode, which will fail on any warnings. Is that worth doing?

**Comment by manics** [comment]
@choldgraf I made warnings into errors in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1610

This picked up some other warnings, but not the broken references in this issue.
