### ISSUE TITLE
Security vulnerabilities with sqlite3

### ISSUE THREAD

**Issue by jackmorgenson** [jupyterhub/zero-to-jupyterhub-k8s#1614]
**k8s-hub:0.8.2**

My threat detection team has alerted me that `sqlite3` in k8s-hub is exposed to a bunch of vulnerabilities that have active attacks known.

[CVE-2019-19926](https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-19926.html)
[CVE-2019-19925](https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-19925.html)
[CVE-2019-19923](https://people.canonical.com/~ubuntu-security/cve/2019/CVE-2019-19923.html)

sqlite3 in k8s-hub is version 3.22.0 in both 0.8.2 and 0.9.0-beta.4, which is understandable since the base is Ubuntu 18.04.

I don't really want to get in the business of maintaining my own customized images.  My k8s environments don't allow root access to containers, so just copying an updated version to a running image won't work.

Is this something that can be addressed with this project or is the only solution to create my own images?

Thanks!

**Comment by manics** [comment]
For the benefit of everyone this is the line where it's installed https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.9.0-beta.4/images/hub/Dockerfile#L20

@jackmorgenson Do you know what the upstream distributer (Ubuntu) view on these vulnerabilities is, since 18.04 is still supported by them?

**Comment by jackmorgenson** [comment]
@manics Looks like Ubuntu updated it a few weeks ago, which was news to me, I hadn't checked for about a month.

https://usn.ubuntu.com/4298-1/

So on the next build, it would get automatically updated?

**Comment by betatim** [comment]
I don't think the 0.8.2 tag will get updated. This means you will have to upgrade your hub to a newer version if you don't want to maintain your own image at the old version.

https://hub.docker.com/r/jupyterhub/k8s-hub/tags lists all the current tags. I was surprised to see the last image was about 1month old. I think this is because no code has changed in the hub image in a while. Is that it?

**Comment by jackmorgenson** [comment]
Sorry, I wasn't clear.  By "next build", I meant the pending release of 0.9.0.

**Comment by consideRatio** [comment]
We need to make any change in the hub Dockerfile or make a tagged release, then the image will be rebuilt. 

I'll push myself to write this changelog and some upgrade instructions and release 0.9.0 this weekend.

**Comment by consideRatio** [comment]
Resolved already!
