### ISSUE TITLE
make proxy name configurable

### ISSUE THREAD

**Issue by dmpe** [jupyterhub/zero-to-jupyterhub-k8s#1616]
Hi, 
in my enterprise case, it would be beneficial if proxy pod (its name to be precise) could be configurable, i.e. I could overwrite it at any point of time - without going into changing template scripts. 

Why: well because there is naming conflict with our apache proxy and i am forced to put jupyter into its own namespace and maintaining an exception to the rule. 
(i know it is best practice, but many services also allow to reconfigure these kinds of names)

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/proxy/deployment.yaml#L6

thanks you for considering it

**Comment by betatim** [comment]
We could include the name of the helm release in the name of the pod. This seems to be pretty standard across other helm charts.

Would this solve you problem? It would solve the name collision but maybe you need to really configure the name of the pod instead of just avoiding the collision.

**Comment by dmpe** [comment]
>his seems to be pretty standard across other helm charts.

Yes, that would be ok. Thank you

**Comment by betatim** [comment]
Do you want to make a PR that implements this idea? This is probably the fastest way to get it done :)

**Comment by consideRatio** [comment]
@dmpe I understand your issue, and it is indeed a flaw of our helm chart not prefixing our resource names with our helm release name. But I'm unhappy about upstreaming a workaround to allow this to be renamed.

This Helm chart is hard to maintain as it is due to its complexity, consider this diagram that I made just to understand the current setup of the proxy-public service.

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBpbl9zdmNbc2VydmljZS9wcm94eS1wdWJsaWNdXG4gICAgb3V0X2RlcFtkZXBsb3kvcHJveHldXG5cbiAgICBzdWJncmFwaCBJblxuICAgIGluX3N2Y1xuICAgIGVuZFxuXG4gICAgc3ViZ3JhcGggT3V0XG4gICAgb3V0X2RlcFxuICAgIGVuZFxuXG4gICAgXG4gICAgc3ViZ3JhcGggTm8gSFRUUFNcbiAgICBpbl9zdmMgLS0-IG5vX2h0dHBbODA6ODAwMF0gLS0-IG91dF9kZXBcbiAgICBlbmRcblxuICAgIHN1YmdyYXBoIE1hbnVhbCBIVFRQU1xuICAgIGluX3N2YyAtLT4gbWFuX2h0dHAgJiBtYW5faHR0cHNcbiAgICBtYW5faHR0cFs4MDpdIC0tPiBvdXRfZGVwXG4gICAgbWFuX2h0dHBzWzQ0MzpdIC0tPiBtYW5fY2hvaWNlXG4gICAgbWFuX2Nob2ljZXtwcm94eS5odHRwcy50eXBlfVxuICAgIG1hbl9jaG9pY2UgLS0-fG1hbnVhbHwgOjg0NDMgLS0-IG91dF9kZXBcbiAgICBtYW5fY2hvaWNlIC0tPnxzZWNyZXR8IDo4NDQzXG4gICAgbWFuX2Nob2ljZSAtLT58b2ZmbG9hZHwgOjgwMDAgLS0-IG91dF9kZXBcbiAgICBlbmRcblxuICAgIHN1YmdyYXBoIEF1dG8gSFRUUFNcbiAgICBpbl9zdmMgLS0-IGF1dG9faHR0cCAmIGF1dG9faHR0cHNcbiAgICBhdXRvX2h0dHBbODA6ODBdIC0tPiBhdXRvX2RlcFxuICAgIGF1dG9faHR0cHNbNDQzOjQ0M10gLS0-IGF1dG9fZGVwXG4gICAgYXV0b19kZXBbZGVwbG95L2F1dG9odHRwc10gLS0-XG4gICAgYXV0b19zdmNbc2VydmljZS9wcm94eS1odHRwXSAtLT5cbiAgICBhdXRvX3BvcnQ4MDAwWzgwMDA6ODAwMF0gLS0-IG91dF9kZXBcbiAgICBlbmQiLCJtZXJtYWlkIjp7InRoZW1lIjoibmV1dHJhbCJ9fQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBpbl9zdmNbc2VydmljZS9wcm94eS1wdWJsaWNdXG4gICAgb3V0X2RlcFtkZXBsb3kvcHJveHldXG5cbiAgICBzdWJncmFwaCBJblxuICAgIGluX3N2Y1xuICAgIGVuZFxuXG4gICAgc3ViZ3JhcGggT3V0XG4gICAgb3V0X2RlcFxuICAgIGVuZFxuXG4gICAgXG4gICAgc3ViZ3JhcGggTm8gSFRUUFNcbiAgICBpbl9zdmMgLS0-IG5vX2h0dHBbODA6ODAwMF0gLS0-IG91dF9kZXBcbiAgICBlbmRcblxuICAgIHN1YmdyYXBoIE1hbnVhbCBIVFRQU1xuICAgIGluX3N2YyAtLT4gbWFuX2h0dHAgJiBtYW5faHR0cHNcbiAgICBtYW5faHR0cFs4MDpdIC0tPiBvdXRfZGVwXG4gICAgbWFuX2h0dHBzWzQ0MzpdIC0tPiBtYW5fY2hvaWNlXG4gICAgbWFuX2Nob2ljZXtwcm94eS5odHRwcy50eXBlfVxuICAgIG1hbl9jaG9pY2UgLS0-fG1hbnVhbHwgOjg0NDMgLS0-IG91dF9kZXBcbiAgICBtYW5fY2hvaWNlIC0tPnxzZWNyZXR8IDo4NDQzXG4gICAgbWFuX2Nob2ljZSAtLT58b2ZmbG9hZHwgOjgwMDAgLS0-IG91dF9kZXBcbiAgICBlbmRcblxuICAgIHN1YmdyYXBoIEF1dG8gSFRUUFNcbiAgICBpbl9zdmMgLS0-IGF1dG9faHR0cCAmIGF1dG9faHR0cHNcbiAgICBhdXRvX2h0dHBbODA6ODBdIC0tPiBhdXRvX2RlcFxuICAgIGF1dG9faHR0cHNbNDQzOjQ0M10gLS0-IGF1dG9fZGVwXG4gICAgYXV0b19kZXBbZGVwbG95L2F1dG9odHRwc10gLS0-XG4gICAgYXV0b19zdmNbc2VydmljZS9wcm94eS1odHRwXSAtLT5cbiAgICBhdXRvX3BvcnQ4MDAwWzgwMDA6ODAwMF0gLS0-IG91dF9kZXBcbiAgICBlbmQiLCJtZXJtYWlkIjp7InRoZW1lIjoibmV1dHJhbCJ9fQ)

I personally is extremely fearful about additional workarounds, but, the issue you describe is certainly real and relevant. So, my suggestion of a fix for this, is to do a proper rework, where we don't add a workaround the proxy deployment, but instead does it right once and for all where we prefix the release name to all of our resources.

## Your situation considered specifically
Hmmm... You have a conflict about the name deployment/proxy, not specifically a pod name which will look like pod-hash1-hash2 where there are two hashes because deployments create replicasets owning the pods.

The name of the proxy will influence the pod names, but what matters is mainly labels they have on them rather than their name, and that will remain if the name is changed.

Hmm... Maybe changing the name of the proxy is reasonable after all.. It may actually work to only change the deployment name, hmm... Then maybe we could add a small configuration of this, but I really don't want to end up needing to maintain backward compability against it, so if so, perhaps under a configuration section like `experimental` or `temporary-workaround` or similarly to really make it clear that this isn't going to be a very reliable solution going onwards.

**Comment by dmpe** [comment]
> where we don't add a workaround the proxy deployment, but instead does it right once and for all where we prefix the release name to all of our resources.

I will contribute here a bit on that and you can then pick it up from me. 0.9.5 is going to look amazing - this and then https://github.com/jupyter/docker-stacks/pull/1052. All of which are going to significantly improve jupyter workflow and deployment. :)

**Comment by consideRatio** [comment]
Thanks for being an active member of this project @dmpe!

As this is a popular topic that has been discussed and considered in many places without clear resolution for a long time, I've decided to close all existing issues and PRs relating to it and refer to a single issue: #1791. In this issue I've done my best to provide a clear and actionable path towards progress.
