### ISSUE TITLE
move helm-charts into a subdirectory

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#164]
it's a bit confusing now that the helm-chart has been merged here what files are for what purpose. It's probably a good idea to make a subdirectory containing the helm charts rather than everything sharing the same root.

**Comment by willingc** [comment]
Yes. Helm charts should go in a subdirectory.

@choldgraf I'm not sure how you have the cost notebook and render set up, but that should move out of the root of the repo too.

**Comment by choldgraf** [comment]
good point @willingc ...right now it's just a mini-python-module with the code to make the graph we want.

The only thing that needs to stay in the root is the build config file so binder will install the dependencies (we can remove that whenever we start supporting `.binder` folders).

I think I should be able to move the jupyter notebook + the module into the `doc` folder, will make that a PR today.

**Comment by yuvipanda** [comment]
Per https://github.com/jupyterhub/binderhub/pull/110#issuecomment-330628529 we're going to move the binderhub chart out of this repository, since it was originally here due to technical limitations that no longer exist. 

The helm chart needs to be in a directory called 'jupyterhub', so our options are `jupyterhub/` or `charts/jupyterhub`. Either is fine with me, but I'd slightly prefer the former :)

**Comment by choldgraf** [comment]
+1 to `jupyterhub/`...we can explain that it contains a helm chart in the readme

**Comment by yuvipanda** [comment]
I'm going to mark this as done, since there's no more jupyterhub and binderhub charts - just a jupyterhub chart.
