### ISSUE TITLE
Cordone nodes with a history of N-sequential failed notebook starts

### ISSUE THREAD

**Issue by snickell** [jupyterhub/zero-to-jupyterhub-k8s#1692]
Over the long haul, we see user-pool nodes very occasionally get trashed (various ways, but SMB mounts and GPU are two common ways) without fully dying. The interactive nature of jupyter notebooks seems to really raise the chance of causing host issues despite container isolation.

The problem is that a single bad node in a large pool will prevent autoscaling, with the k8s control plane trying that node over and over and over for starting notebooks. The result is a total inability to login by anyone, and an inability to autoscale.

It'd be nice if there was an easy hook to allow cordoning (or even just alerting) user-pool nodes that seem to be having trouble starting notebooks. Even figuring some sort of hub metric for tracking nodes which have had N-sequential start failures (and how many different users were in the list of failures?), could be the start of a good homebrew approach to this.

**Comment by consideRatio** [comment]
Sad to hear about that much node issues, what cloud provider is this running on?

I don't see it as something in scope to monitor for failing nodes, as it is something that can be a standalone project without without need for a coupling to this Helm chart. I'll close this issue due to that, but I agree, it sounds important to have something that helps node recover or similarly.

I have not needed it as far as I know, but GKE has a checkbox for _node autorepair_, perhaps that is about catching various issues with node and restarting them.
