### ISSUE TITLE
Automate updating image dependencies

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#1753]
As mentioned in #1752 by @jgwerner, it could be cool/convenient to automate PRs bumping the requirements in the hub image, either with a GitHub action or [dependabot config](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-github-dependabot-version-updates).

We have started using pip-tools (with some wrapping to run it inside our image to ensure equivalence) for the hub image, but we could probably drop the wrapper if we ran pip-compile in CI or via dependabot. Dependabot [does support pip-compile](https://dependabot.com/blog/dependabot-now-supports-pip-compile/) so this might be pretty simple!

**Comment by jgwerner** [comment]
Thanks for the mention @minrk - we could give a go at this if you'd like!

**Comment by consideRatio** [comment]
Thanks the summary @minrk!

Related to this kind of work is automated scanning of dependencies that may have become outdated etc. Perhaps this work could be a building block to be triggered by an automated security scan as well. I don't yet understand fully what depandabot triggers on etc.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1712

@jgwerner feel free to ping me for review of the dependabot work, I'm interested in learning about it!

**Comment by jgwerner** [comment]
@consideRatio we will do our best to send a POC PR this week to test this integration and will ping you for sure 👍

**Comment by jgwerner** [comment]
@consideRatio @minrk apologies for taking so long to get back to this!

I held back a bit since GH was transitioning the Dependabot to a more native [configuration yaml](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates). We have been testing the service in our org and the bot does pick up on the python dependency updates quite well. Since you are using `pip-compile` and the source packages are managed in `*.in` files I believe (it's possible that I'm still not understanding these options in particular) this setup would need to set the `versioning-strategy` to `lockfile-only`.

I submitted #1844 for review, let me know if you would like me to update any of the settings.

**Comment by consideRatio** [comment]
Thanks for your work on this @jgwerner :heart: I love the outcome!
