### ISSUE TITLE
Rewrite hook-image-awaiter with Rust and its Kubernetes client library: clux/kube-rs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1786]
@yuvipanda wrote

> I think it would be good to rewrite the hook awaiter in https://github.com/clux/kube-rs. Unlike with Go, I think we can actually use this [kubernetes client] library, and binary static size should be comparable.

## Background
The image awaiter is a small binary written in Go to be a very small image that can quickly startup. Its purpose is to await for a daemonset's pod to be successfully scheduled and running, but it is also as of #1763 able to stop waiting for pods not successfully scheduled and only await those that are running.

## Motivation
To reduce the code complexity of the code base by relying on a libraries for Kubernetes interactions instead of doing it manually with raw HTTP request. In a way it would increase the complexity by bundling with a Kubernetes client library, but I think this makes sense as well.

@yuvipanda what would you describe the key motivation for this rewrite would be?

**Comment by yuvipanda** [comment]
Thanks for opening this, @consideRatio!

The original motivation for writing this in Go is the very small binary size, so that the image will start up very quickly. However, we couldn't really include the upstream kubernetes client library - it was large, and at that point there was no real Go dependency management system. So we sort of wrote our own micro-client that just does what we want.

However, this sucks! We shouldn't be writing our own http clients for k8s APIs. It would be nice to use a library for this. Go's package management system has gotten better. So we could use that too. But Rust seems more aligned with Python in general, so the suggestion was to use Rust for this.

**Comment by consideRatio** [comment]
Thank you @yuvipanda, lets go for Rust! :)

**Comment by consideRatio** [comment]
I figure what we have currently works well and reliably and have been documented a bit extra from the developer perspective to help us manage with Golang as a somewhat odd language within the JupyterHub org.

I suggest we go for a close of this issue as the change would lead to additional work in review maintenance even if someone championed the PR.
