### ISSUE TITLE
 PR Discussion - block user-placeholder pod eviction temporarily based on node's single user image locality

### ISSUE THREAD

**Issue by donotpush** [jupyterhub/zero-to-jupyterhub-k8s#1836]
The user-placeholder Statefulset and the continuous-image-puller Daemonset relies completely on Kubernetes pod eviction algorithm (based on the given pod priority) to choose which user-placeholder pod will be evicted to schedule a new user pod.

Considering a Jupyterhub setup like the following:

- Google Kubernetes Engine 
- User-placeholder pod resources limits/guarantees equal to VM’s resources
- A heavy single user docker image bigger than 5GB
- Considerable amount of users launching and stopping servers 
- Every user gets its own VM, the base VM image does not contain the docker single user image, we rely on continuous-image-puller to do its job.
- Three or more user-placeholder replicas

Based on my experience, Kubernetes always evicts the youngest user-placeholder pod, and in my case the youngest pod is always a recently scaled node/VM instance. This is a problem because there is a time window of approximately 3-5 min where the new node is downloading the docker image. When a user launches a server inside that time window, Kubernetes will assign the new user pod to a node that does not have that heavy docker image pulled, yet ignores the older nodes that already have the image.

As a result, users are experiencing a longer boot time than expected even when the user-placeholder is enabled.

### Proposed change

The only solution that I have found to tackle the issue described above is combining the usage of user-placeholder and continuous-image-puller with an application that adds and removes temporal `node taints`. [Nidhogg](https://github.com/uswitch/nidhogg) seems to do the job quite well.

```
Nidhogg is a controller that taints nodes based on whether a Pod from a specific Daemonset is running on them.
Sometimes you have a Daemonset that is so important that you don't want other pods to run on your node until that Daemonset is up and running on the node. 
Nidhogg solves this problem by tainting the node until your Daemonset pod is ready, preventing pods that don't tolerate the taint from scheduling there.
```
These nodes’ taints are added and removed based on the continuous-image-puller Daemonset status, which is only `ready` when the single user docker image has been pulled. 

The usage of Nidhogg + a small modification on the helm chart that adds an exclusive Nidhogg toleration in the continuous-image-puller Daemonset solves the issue described above. 

Would you be interested in adding this modification and perhaps a Nidhogg dependency to the upstream Jupyterhub Helm Chart?

### Who would use this feature?

Anyone that has a considerable amount of users, and is experiencing user-placeholder pod eviction order issues.

**Comment by consideRatio** [comment]
## General notes
I think the algorithm of scheduling a pod, with the modern kube-scheduler binary we have and Kubernetes system in general, is to first decide if there is any nodes that could be considered acceptable. Tainted nodes we don't tolerate are excluded here for example. Then these are ranked, and then evictions are done

## Goal assumption
To schedule on a node where the needed images are already pulled or the node being closest to getting them pulled, while at the same time prioritizing scheduling on the most busy node as the most important priority.

## Considerations
- It is not optimal for a pod to wait for all images to be pulled on a node, but only the specific images it needs, which most often but not always is part of what the continuous-image-puller pulls. So, tainting a node for not having exactly all images can degrade user experience.
- It adds complexity to introduce various configurations that can be tweaked, and it requires more documentation to be maintained and consumed. Due to this, preferably, we have a one size fit all kind of solution which is good for everyone. If the compromise from the one-size-fits-all solution for some users, then it could motivate additional customization.

## Solution ideas
The user-scheduler was remade to use a more modern version of kube-scheduler a month ago, and is still backward compatible for k8s versions 1.15 and lower by using the old implementation. We will only focus on the new implementation of the user-scheduler that relies on the modern kube-scheduler binary and its configuration options.

Here is the default configuration we pass to the user-scheduler, which is a kube-scheduler binary configuration:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/9ca120bb8935d465caab3eb7e9d41c04e5052f67/jupyterhub/values.yaml#L360-L368

As seen, we are disabling the image locality part, I didn't learn as I have now, that we can adjust the weights of how we score nodes, and I wanted us to prioritize scheduling on the most busy node. But, if two nodes are equally busy, then we could schedule on the one with image locality.

From the example here: https://kubernetes.io/docs/reference/scheduling/config/#extension-points, I conclude that we can use weights here. So, I'll go ahead and fix that now.

**Comment by consideRatio** [comment]
The old implementation had weights like this:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/9ca120bb8935d465caab3eb7e9d41c04e5052f67/jupyterhub/files/userscheduler-defaultpolicy.yaml#L19-L25

**Comment by consideRatio** [comment]
@donotpush if you have time before we have a chat, consider what you think about simply making user-scheduler (in a k8s 1.16+ cluster using the new implementation) start caring about ImageLocality like the older user-scheduler does (in a k8s 1.15 or older k8s cluster).

**Comment by donotpush** [comment]
@consideRatio this looks great, I am going to test it out.

**Comment by consideRatio** [comment]
@donotpush the issue
