### ISSUE TITLE
pull-all-nodes requires docker.sock

### ISSUE THREAD

**Issue by Stibbons** [jupyterhub/zero-to-jupyterhub-k8s#213]
Hello

I am trying to integrate JupyterHub inside our in-house Kubernetes infrastructure, but I get an error during deployment: **pull-all-nodes fails with error regarding docker.sock**

    ,OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:PodSpec{Volumes:[{docker-socket {HostPathVolumeSource{Path:/var/run/docker.sock,} nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil}}],Containers:[{puller yuvipanda/image-puller:v0.2 [] [jupyterhub/k8s-singleuser-sample v0.4]  [] [] {map[] map[]} [{docker-socket false /var/run/docker.sock }] nil nil nil   nil false false false}],RestartPolicy:Never,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[],Hostname:,Subdomain:,},},},Status:JobStatus{Conditions:[],StartTime:<nil>,CompletionTime:<nil>,Active:0,Succeeded:0,Failed:0,},} &TypeMeta{Kind:,APIVersion:,}  false}
from server for: "STDIN": the server does not allow access to the requested resource (get jobs.batch pull--v0-4-1507132131)

There is no reason to access to the docker socket, since there is Tiller with the right privildges, and kubectl can pretty much do all the job anyway

**Comment by yuvipanda** [comment]
Heya! It does require docker.sock, since it pulls the singleuser server image on all nodes before doing the deployment. We do this so when users launch their pods, it launches quickly without waiting for a full pull.

There isn't any way for us to trigger this with kubernetes directly, so unfortunately we do require access to docker.sock. You can disable prepuller by setting `prePuller.enabled` to false in your config.yaml.

The long term fix for this is to have a CRD for Image Pre Pulling and implement that properly. We haven't had time to do that yet, however.

**Comment by Stibbons** [comment]
Thanks for the answer. Cannot Tiller do it, since it is running on the server with extra priviledges?

**Comment by yuvipanda** [comment]
@Stibbons unfortunately not, since that is not a functionality that Tiller provides.

**Comment by Stibbons** [comment]
Thanks for your answer !
