### ISSUE TITLE
something is wrong with the documentation

### ISSUE THREAD

**Issue by parmentelat** [jupyterhub/zero-to-jupyterhub-k8s#2189]
at least one html page on rtd exhibits a couple occurrences of a formatting problem 

in
https://zero-to-jupyterhub.readthedocs.io/en/stable/jupyterhub/installation.html

I could spot stuff like the following; 

![image](https://user-images.githubusercontent.com/4519227/117774059-60b09f80-b239-11eb-8165-4b0846a1c182.png)

![image](https://user-images.githubusercontent.com/4519227/117773885-2810c600-b239-11eb-992f-e7c399a94250.png)

![image](https://user-images.githubusercontent.com/4519227/117773896-2cd57a00-b239-11eb-8fe2-ff64af1f65e7.png)

looking a bit further down the docs, I could find at least one similar issue in
https://zero-to-jupyterhub.readthedocs.io/en/stable/jupyterhub/customizing/user-environment.html

so it could well be a widespread problem

**Comment by consideRatio** [comment]
@parmentelat thanks for reporting this!

At least those examples you found have been fixed in the latest version of the documentation, but we haven't backported the change to previous released versions of the documentation. When viewing the documentation you can view the `stable` version or the `latest` version. `stable` represents the latest release, while `latest` represents the latest state of the git repository.
