### ISSUE TITLE
Doc bug: postgres connection string is not supported as of n495

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/zero-to-jupyterhub-k8s#2205]
### Bug description
After a clean install of n495 on x64 AKS I can't connect to my postgres JH database. 

The example connection string in the documentation [here ](https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html) is: 

postgres+psycopg2://<db-username>:<db-password>@<db-hostname>:<db-port>/<db-name>

Using this connection string yields the following error

```
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres.psycopg2
```

Per this SO https://stackoverflow.com/questions/62688256/sqlalchemy-exc-nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialectspostgre that postgres needs to be postgresql and this indeed fixed my issue.

### How to reproduce

Clean install of n495 with connection string from documentation.

### Your personal set up

AKS 1.20.5

**Comment by manics** [comment]
Sorry about that, it's already fixed in the latest doc: `postgresql+psycopg2://<db-username>:<db-password>@<db-hostname>:<db-port>/<db-name>` https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html
This will become the stable doc in our next release (which should be happening very soon!
