### ISSUE TITLE
Config Templates

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/zero-to-jupyterhub-k8s#222]
It would make sense to have sample config templates and perhaps a script to generate templates

**Comment by yuvipanda** [comment]
Here are some examples:

http://github.com/yuvipanda/paws
http://github.com/berkeley-dsep-infra/datahub/

**Comment by yuvipanda** [comment]
I'm a big fan of having cookiecutters that generate entire repos off a few questions. I think an easy first step is to just have fully commented sample config.yaml files for different use cases (workshop, classes, etc?). I don't think we should write a script yet, since that adds another layer of abstraction for people to understand on top of already many layers of abstraction

**Comment by consideRatio** [comment]
Closing in favor of #876
