### ISSUE TITLE
Jupterhub hub pod is failing

### ISSUE THREAD

**Issue by mathewsg** [jupyterhub/zero-to-jupyterhub-k8s#2239]
we are observing that the hub pod is getting into failed state with the error "connection timeout out with mysql server". After setting mysql pool_recycle value to 300, the frequency of failures got reduced, but still we are observing the issue.

Jupterhub chart version : jupyterhub-0.10.6
Azure kuberenets version: 1.19.7
Hub version : jupyterhub/k8s-hub: 0.10.6-n211.h2e3a73af
Azure My SQL version: 5.7

how can we avoid this issue with hub pods ?

**Comment by consideRatio** [comment]
I don't know, but it is at least out of scope for this to be an issue in the Helm chart. It may be in scope to be an issue in jupyterhub/jupyterhub.

I don't have knowledge of what it means to set that configuration you mention, and I can't even google properly on it because its not documented so clearly how you configure it. I'll go ahead and close this issue here as I find it too hard to decide if this is an issue in the Helm chart, jupyterhub, your configuration of mysql, your configuration of networking, or some issue in mysql etc.

I think until you have more clarity about this to be a concrete issue with action points on what to change or that something needs to change in a certain repo, I suggest that you open a question in discourse.jupyter.org.

I'm sorry I can't be more helpful than this @mathewsg =/
