### ISSUE TITLE
Include provider-general kubernetes teardown instructions

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#225]
I just got dinged with a $150 charge from Amazon because I had mistakenly been running 150 volumes on EC2 that were created for users. If I would have followed the kubernetes teardown instructions instead of the "amazon button clicking" instructions this would have been avoided. We need something like

`kubectl delete ns <namespace>`

at the beginning of the tear-down page, and follow that with more provider-specific instructions if needed. (@yuvipanda can you confirm this is right?)

**Comment by yuvipanda** [comment]
There should be two steps:

## Non cloud provider specific

1. helm delete <release-name> --purge
2. kubectl delete ns <namespace-name> 
3. Do 'kubectl get ns' until the namespace is gone

## Cloud provider specific

What we already have


In addition, for google cloud, if they push an image to gcr.io, they should probably delete that too, since that might incur a cost (even though it's usually cents a month). For Google we should also show people how to delete the project, since that's foolproof. Maybe there's an equivalent for AWS?
