### ISSUE TITLE
Using CSI driver from openebs fails to mount PVCs

### ISSUE THREAD

**Issue by Atharex** [jupyterhub/zero-to-jupyterhub-k8s#2391]
### Bug description

Recently I've updated both OpenEBS as my storage provider to 2.12.1 using the cStor CSI plugin
and ZTJH to 1.1.3

In these versions, the hub seems to give trouble connecting the openEBS PVC to the JH provisioned pod.
When I spin up a user pod, I get the following warning output in kubectl describe pod:

`2021-09-19T07:46:00Z [Warning] MountVolume.MountDevice failed for volume "pvc-ed35b156-ec20-4708-b6d5-a2d946167e1b" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name cstor.csi.openebs.io not found in the list of registered CSI drivers`

This warning seems to be a bit misleading, as I am successfully using the same provisioned PVCs for all other projects, except Jupyterhub. The CSI driver is loaded and available, but Jupyterhub for some reason does not load it:

```
kubectl get csidriver
NAME                   ATTACHREQUIRED   PODINFOONMOUNT   MODES                  AGE
cstor.csi.openebs.io   false            true             Persistent,Ephemeral   3d1h
```

#### Expected behaviour
Jupyterhub should use the provisioned PVC and successfully attach it to the user pod

#### Actual behaviour
Jupyterhub throws a warning that this particular CSI driver is not found and then timeouts while failing to provision the prepared PVC to a user pod

## # How to reproduce
Attempt to install the helm charts 
ZTJH - 1.1.3
OpenEBS - 2.12.6 (with cStor persistent storage)

### Your personal set up
K8s version 1.19.10 and above mentioned helm charts
Centos 7
Python 3.8.9

**Comment by consideRatio** [comment]
You experience a problem, and it looks related to this Helm chart's resources because things work for other resources. But in the end, this is a k8s pod that hasn't successfully started, and a PVC that is by no means unique to the Helm chart.

I suspect this is still unrelated to this Helm chart, and debugging to find out if it was unrelated to the Helm chart takes too much time. Until this is pinpointed to something more concrete that this Helm chart should change to work with your k8s cluster, I consider this a support question and ask that you visit discourse.jupyter.org for assistance. 

My debugging technique would be to try reproduce this by creating a single PVC and then a single Pod mounting that PVC, and make that pod as boring as possible. I'd use an example by googling and `kubectl apply -f <example-pod-yaml-file>` etc. Then, if you have something that works to mount a PVC on a Pod, then compare that YAML with the `hub` Pod and `hub` PVC.
