### ISSUE TITLE
singleuser custom resources based on user

### ISSUE THREAD

**Issue by chrisroat** [jupyterhub/zero-to-jupyterhub-k8s#2422]
### Proposed change

I would like to specify different resources depending on username, or at least by admin/regular user.  

My exact use case is mounting volumes using K8s secrets containing credentials for accessing cloud storage.  Admin users have read-write access, while other users have read-only access.

### Alternative options

Admin users manager can load their own credentials.   This is messy, since different tools and libraries use different strategies: env vars, key files, config files, etc.    Admins figure out how to update their environment properly for one tool, but then another tools doesn't work... leading to confusion.  It's smoother to let the deployment environment consistently set up the credentials.

### Who would use this feature?

Anyone managing credentials or resources that need to be different between users.

### (Optional): Suggest a solution

Possible ideas:
- Have two additional fields for extra resource specifications, one for admins and one for normal users.
- Similar to profileList, have a way to specify of list of possible resources, linked to user type or user name.
- In dask-gateway, there is an optionHandler method that allows custom python code to update configs programmatically.  Something similar could allow very flexible resource specs.

**Comment by manics** [comment]
Is this something that would only ever work with Kubespawner, or do you think it could be made more generic? https://github.com/jupyterhub/wrapspawner is an example of generalising the profile list for all spawners, and there's been previous discussion about removing the kubespawner specific profiles and using wrapspawner instead: https://github.com/jupyterhub/kubespawner/issues/447

**Comment by consideRatio** [comment]
I think there is an never ending need for customizations if we tailor customizations on this level. I think the only solution is to provide full control to the chart user to customize things with arbitrary logic.

I've written a post on how to do these kinds of customizations on discourse, see https://discourse.jupyter.org/t/tailoring-spawn-options-and-server-configuration-to-certain-users/8449.

**Comment by chrisroat** [comment]
Thanks!  That post looks super helpful.  I'm not familiar with the spawner.  A couple of questions:
- I am looking for find out of the user is part of `hub.config.GoogleAuthenticator.admin_users`.  Is that possible?
- Can the python code demonstrated in the post be given as a `singleuser.extraConfig` (much as I do for `hub.extraConfig`)?   [If so, I could customize that in my yaml with the same list I set for `hub.config.GoogleAuthenticator.admin_users`.]

**Comment by consideRatio** [comment]
> I am looking for find out of the user is part of hub.config.GoogleAuthenticator.admin_users. Is that possible?

I think that may be a property of the user, and you can acquire information about the user.

> Can the python code demonstrated in the post be given as a singleuser.extraConfig

Hmmm, anything related to configuration about the Spawner must be configuration specific for the hub pod where JupyterHub and the spawner run. Adding anything to `singleuser.` wouldn't make sense. You can use `singleuser.extraFiles` if you want to inject some configuration file etc if thats relevant, but anything you configure there is unrelated to the logic deciding how that entire k8s pod/container is started up by the logic configured for JupyterHub (running in the hub pod, and configured via `hub.` in the Helm chart).

I think you can do this....

```python
async def custom_pre_spawn_hook(spawner):
    # Here are examples of information available to us:
    #
    # 1. Info about the user from the JupyterHub User object
    #
    username = spawner.user.name
    admin = spawner.user.admin
```

Because I note that there is an `admin` field for the user database representation which I believe you are interacting with when calling `spawner.user`. See https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#/definitions/User.

**Comment by consideRatio** [comment]
I updated the discourse post to include the reference to the User object's misc properties available.
