### ISSUE TITLE
Jupyterhub on Kubernetes with numerous continuous-image-puller pods 

### ISSUE THREAD

**Issue by aloifolia** [jupyterhub/zero-to-jupyterhub-k8s#2470]
### Bug description
I followed the [installation guide](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html) to get Jupyterhub working on a k8s cluster. From a user's perspective, everything is fine. However, I noticed, that numerous continuous-image-puller pods have been created. Also, the number seems to be increasing. The current count is 24. Until now, two user accounts have been created.

Is this behavior expected? This was not documented anywhere, so I guess this might be a bug.

### Your personal set up
The command I use to install or upgrade jupyterhub is

```
helm upgrade --kubeconfig kube-config.yml --cleanup-on-fail --install v1 jupyterhub/jupyterhub --namespace rids-jupyter --create-namespace
```

There is no customization, yet.

**Comment by consideRatio** [comment]
> However, I noticed, that numerous continuous-image-puller pods have been created. Also, the number seems to be increasing. The current count is 24. Until now, two user accounts have been created.

There is documentation about the continuous-image-puller at: https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html?highlight=continuous-image-puller#pulling-images-before-users-arrive

If you have 24, it means you have 24 nodes in the k8s cluster where the user pods are allowed to spawn in practice. If the number is increasing, it means you are starting more and more nodes in the k8s cluster.

You can disable this function, which helps users arrive to nodes with the image already downloaded, you can read in the docs there how to disable it.

I'm not sure how the documentation should be improved in a fairly easy to describe way, in order to make your experience as a user better. If you have ideas about that please try to describe it, otherwise I figure we'll go for a close without taking any action.

**Comment by aloifolia** [comment]
I was probably misreading the guide, then. Your explanation now clears things up for me.
