### ISSUE TITLE
using baseUrl and oauth results in hub/hub redirect

### ISSUE THREAD

**Issue by sneely333** [jupyterhub/zero-to-jupyterhub-k8s#2490]
description
Using the helm config option baseUrl and GenericOAuthenticator (with Cognito) directs user to https://$domainname/$baseurl/hub/hub after successful authentication.  If the user removes the second hub in the url, everything works as expected.  All other links also work as expected.

Expected behaviour
oauth would direct to / rather than /hub.

Actual behaviour
oauth redirects to /hub which, because of the baseUrl being set, directs to baseUrl/hub/hub. 

### How to reproduce
Use the standard helm install, set

```yaml
hub:
 baseUrl: /ondemand

config: 
   GenericOauthenticator: 
      etc etc
```

My set up
Using zero-to-jupyterhub with eks and helm

Chart: jupyterhub-0.11.1
App version: 1.3.0

Relevant Logs: 
```
[I 2021-11-19 02:53:18.982 JupyterHub oauth2:104] OAuth redirect: 'https://example.com/ondemand/hub/oauth_callback'
[I 2021-11-19 02:53:18.983 JupyterHub log:181] 302 GET /ondemand/hub/oauth_login?next=%2Fhub%2F -> https://example.auth.us-west-2.amazoncognito.com/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fondemand%2Fhub%2Foauth_callback&client_id=xxxxxxxxxx&state=[secret] (@::ffff:ip) 1.43ms
[I 2021-11-19 02:53:19.588 JupyterHub base:757] User logged in: example_username
[I 2021-11-19 02:53:19.588 JupyterHub log:181] 302 GET /ondemand/hub/oauth_callback?code=[secret]&state=[secret] -> /hub/ (@::ffff:ip) 386.39ms
[I 2021-11-19 02:53:19.977 JupyterHub log:181] 302 GET /hub/ -> /ondemand/hub/hub/ (@::ffff:ip) 0.62ms
[W 2021-11-19 02:53:20.103 JupyterHub log:181] 404 GET /ondemand/hub/hub/ (example_username@::ffff:ip) 6.52ms
```

**Comment by minrk** [comment]
The origin bug is here, in the first line:

```
 302 GET /ondemand/hub/oauth_login?next=%2Fhub%2F
```

That _should_ be `?next=%2Fondemand%2Fhub%2F`, but it is missing the base_url prefix. Can you include the previous few log lines, which should include the redirect _to_ `/oauth_login`? Usually, `?next=` is the URL visited before logging in, but sometimes it can be a default value or come from config.

Ultimately, the issue is that the final redirect is to an unhandled `/hub/` url (without prefix), which gets redirected to the _hub_ prefix (/ondemand/hub/hub/). It should probably just 404.

**Comment by sneely333** [comment]
I was curious about that line but it seems to autofilled and I couldn't find a config option to change it.  Since all other links work, I thought it might be something specific to oauth_callback.

Here is the log starting from me logging out:
[I 2021-11-19 02:53:16.813 JupyterHub log:181] 302 GET /ondemand/hub/logout -> /ondemand/hub/login (@::ffff:ip) 4.72ms
[I 2021-11-19 02:53:16.870 JupyterHub log:181] 200 GET /ondemand/hub/login (@::ffff:ip) 15.57ms
[I 2021-11-19 02:53:17.120 JupyterHub log:181] 302 GET /static/custom_assets/images/51_example-home.jpg -> /ondemand/hub/static/custom_assets/images/51_example-home.jpg (@::ffff:ip) 0.77ms
[I 2021-11-19 02:53:17.162 JupyterHub log:181] 302 GET /static/custom_assets/images/logo_company@2x.png -> /ondemand/hub/static/custom_assets/images/logo_company@2x.png (@::ffff:ip) 0.71ms
[I 2021-11-19 02:53:17.164 JupyterHub log:181] 302 GET /static/custom_assets/images/menu_button_company@2x.png -> /ondemand/hub/static/custom_assets/images/menu_button_company@2x.png (@::ffff:ip) 0.59ms
[I 2021-11-19 02:53:17.165 JupyterHub log:181] 302 GET /static/custom_assets/images/sso_login_button@2x.png -> /ondemand/hub/static/custom_assets/images/sso_login_button@2x.png (@::ffff:ip) 0.50ms
[W 2021-11-19 02:53:17.318 JupyterHub log:181] 404 GET /ondemand/hub/style.min.css.map (@::ffff:ip) 15.35ms
[I 2021-11-19 02:53:18.982 JupyterHub oauth2:104] OAuth redirect: 'https://example.com/ondemand/hub/oauth_callback'
[I 2021-11-19 02:53:18.983 JupyterHub log:181] 302 GET /ondemand/hub/oauth_login?next=%2Fhub%2F -> https://example.auth.us-west-2.amazoncognito.com/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fondemand%2Fhub%2Foauth_callback&client_id=xxxxxxxxxxxxxxx=[secret] (@::ffff:ip) 1.43ms
[I 2021-11-19 02:53:19.588 JupyterHub base:757] User logged in: example_username
[I 2021-11-19 02:53:19.588 JupyterHub log:181] 302 GET /ondemand/hub/oauth_callback?code=[secret]&state=[secret] -> /hub/ (@::ffff:ip) 386.39ms
[I 2021-11-19 02:53:19.977 JupyterHub log:181] 302 GET /hub/ -> /ondemand/hub/hub/ (@::ffff:ip) 0.62ms
[W 2021-11-19 02:53:20.103 JupyterHub log:181] 404 GET /ondemand/hub/hub/ (example_username@::ffff:ip) 6.52ms

**Comment by minrk** [comment]
If I read the logs right, it's clicking the login button that's producing the link `/ondemand/hub/oauth_login?next=%2Fhub%2F`. That gives me somewhere to look! To double check, when you look at the login page, can you inspect the 'login with' link and the URL when you see the button, and verify that:

- the URL in the browser is `/ondemand/hub/login` (no url params), and
- the "Login with..." link is `/ondemand/hub/oauth_login?next=%2Fhub%2F`


I'm trying to reproduce this, but I can't seem to get it to misbehave in the same way. 

Current hunch: Do you perhaps have any custom templates? I see various custom static assets, which suggest there are some _and_ they have incorrect hardcoded URLs in them (`/static/` instead of using `{{static_url("custom_assets/...")}}`. Would it be possible to share some or all of the custom HTML template? Is there a chance you have a custom login link that might hardcode `?next=/hub/` or similar?


---

How I read the logs:

- `200 GET /ondemand/hub/login` serves the login page with the `login with...` link. It has no URL params.
- some custom static assets with `/static/` suggest there's a custom template with hardcoded `/static/` URLs
- `302 GET` for the oauth_login URL suggests it was visited by clicking a link rather than auto-login redirect. This has the incorrect `?next=...` in it, which suggests the erroneous `?net` is added in the HTML of the login page since it was not inherited by the request _for_ the login page.

**Comment by sneely333** [comment]
you are absolutely right - thank you so much!  It was buried in there.

**Comment by minrk** [comment]
Excellent! Wonderful that there happened to be that typo in the static assets, I'm not sure custom templates would have occurred to me, otherwise. OK to close?

**Comment by sneely333** [comment]
absolutely, please close and thank you again
________________________________
