### ISSUE TITLE
jupyterhub/k8s-hub:v0.4 does not have a user with UID 1000

### ISSUE THREAD

**Issue by MarkusTeufelberger** [jupyterhub/zero-to-jupyterhub-k8s#252]
/jupyterhub/values.yaml wants to run commands in the container as UID 1000. In /etc/passwd in the image however there is no user with that ID.

**Comment by choldgraf** [comment]
I *believe* this issue has been fixed in the soon-to-be-released v0.5 helm chart, right @yuvipanda ?

**Comment by yuvipanda** [comment]
The problem here is that on master we are still using 'v0.4' as the tag, when in reality we should be using a tag from https://hub.docker.com/r/jupyterhub/k8s-hub/. 

@MarkusTeufelberger if you use a recent tag from there, this problem should go away. 

@choldgraf this is only partially related to v0.5. We should probably swap out the master tag to something that works out of the box, since this seems to bite a lot of people!

**Comment by MarkusTeufelberger** [comment]
I would expect your CI test(s) to fail though with the current configuration.

Looking at the tags there I'm not sure which one is considered stable, the ones that don't just look like random hashes _after_ v0.4 are:

* v0.05a
* v0.5a
* vv0.5a
* v0.1

Neither of those sound stable and container sizes vary dramatically. Is any tag there corresponding to an actual release or supported? How are these containers created and by whom?

**Comment by yuvipanda** [comment]
The containers are created by our CI process (from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/build.py). The random hashes are the commit hashes - so you should use the version of image that matches the commit hash of the helm chart you are using. We'll release v0.5 hopefully this or next week and that'll be a better supported version.

When developing locally, I usually just call ./build.py --image-prefix=yuvipanda/k8s build --push to modify values.yaml in a way that lets me work locally. Can you try that? We don't have very good docs on running off master yet, sorry :(
