### ISSUE TITLE
UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "hub-db-dir"

### ISSUE THREAD

**Issue by snickell** [jupyterhub/zero-to-jupyterhub-k8s#2570]
Hi! Lately when I try to `helm upgrade myz2jh` my z2jh installation on prod or staging, I'm getting the following error:
```
Step #7: Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "hub-db-dir" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
Step #7:   core.PersistentVolumeClaimSpec{
Step #7:   	AccessModes:      {"ReadWriteOnce"},
Step #7:   	Selector:         nil,
Step #7:   	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
Step #7: - 	VolumeName:       "",
Step #7: + 	VolumeName:       "pvc-7bffbe5b-3b84-4900-88f9-199cd1ee1148",
Step #7: - 	StorageClassName: nil,
Step #7: + 	StorageClassName: &"standard",
Step #7:   	VolumeMode:       &"Filesystem",
Step #7:   	DataSource:       nil,
Step #7:   }
```

I work around it by completely deleting PVC `hub-db-dir`, and then setting its finalizers to null with kubectl patch,  before each upgrade in my deploy now, but of course, that's going to cause *serious* problems! And it comes back before the next deploy.

Maybe this is an issue with newer helm versions (I have helm == 3.7.1)?

**Comment by consideRatio** [comment]
I suspect your k8s cluster rather than the helm chart, perhaps the helm cli has a bug but hmmm...

Use the "helm template" command and render both old/new version you upgrade from/to, then inspect if the rendered PVC resource is different. If it is, then it could be the helm chart's fault and something to fix.

When using the helm template command, for simplicity, i recommend using --repo, --version, and --show-only flags to make it easy to compare the rendered pvc template (--show-only templates/hub/pvc.yaml) for different versions of the helm chart.

**Comment by snickell** [comment]
Hi @consideRatio , the k8s cluster is GKE. I'm starting to suspect the issue has to do with changes in recent k8s releases to how k8s dynamic volumes are provisioned. The generated helm is the same in both cases, but after deploy, when the volume claim is used, the volumeName object is being set to the bound/associated volume.

**Comment by snickell** [comment]
If anyone else encounters this upgrade problem, I was able to resolve it by explicitly setting:
```
hub:
  db:
    pvc:
      storageClassName: '' # the default is nil, which means if there are multiple drivers, dynamic provisioning is used, which is what is causing the problems for helm because it modifies the PVC when the volume is bound
```

Weird, right? Here's why....

Like many k8s clusters, we run a number of services on ours. It looks like deploying a k8s CSI driver to one of our pods in the same namespace makes 'storageClass: nil' no longer a fixed reference, and dynamic provisioning starts kicking in. With no storageClass set, once in dynamic provisioning "mode" (this is by observation, I haven't found this in the k8s csi specs yet, but minikube does it too, so I suspect its spec-behavior), ambiguous storageClasses appear to be resolved by the cluster editing the PVC spec with the bound volume name (in my case: ceres-flights, as per normal, helm failed patch diffs are imo "reverse diffs" from sane".

It appears that the cluster internally self-modifying the immutable PVC in this way is permitted, but not externally with helm.

Helm doesn't appear savvy to this behavior yet, so it tries to PATCH the PVC to remove the volumeName (=trying to set it to nil, when its now `spec.volumeName = pvc-blahblahblahuuidblahuuid`), and the now-bound storage-class (=trying to set it back to nil, when its now, in my case 'standard'). This of course fails, because the PVC is immutable.

In other words:
1.  hub-db-dir spec is deployed by helm *without* volumeName and storageClass properties
2. if CSI is in use in the namespace, the now-ambiguous-nil-storage-class is repaired by the k8s layer (probably the csi layer?), adding volumeName and storageClass properties to the other-wise immutable PVC
3. when you try to re-deploy with helm, it tries to remove the dynamically-added-by-k8s volumeName and storageClass properies, but it can't, because they are immutable (also `helm --force` doesn't fix this as of helm 3 regressions, ugh)

Solution: `storageClass: nil` is NOT defined by the k8s spec to mean the same thing as `storageClass: ''`. If hub-db-dir was deployed with `storageClass: ''` (instead of being absent if not set, absent is the current default behavior if you don't override values.yaml `hub.db.pvc.storageClass`), then it would NOT be dynamically provisioned according to the PVC spec, which I believe is actually closer to the correct behavior for a ReadWriteOnce volume (since sqlite can't handle multiple readers anyway).

Perhaps `hb-db-dir` should default to '', instead of being wrapped in an "if/then" that leaves it nil, if `hub.db.pvc.storageClass` isn't expclitily overriden?

I don't think you want hub-db-dir dynamically provisioned.

**Comment by snickell** [comment]
I think this is primarily a helm snafu, I've seen a number of other small github projects running into this too, I suspect as CSI becomes more common, no useful resolutions yet.

According to the PVC docs, what z2jh does is theoretically good default behavior: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration

But CSI+helm might change that rec in the wild as CSI becomes more common?

**Comment by snickell** [comment]
Here we go, I think CSI is affecting whether the DefaultStorageClass plugin admission plugin is enabled, which ends up triggering this helm problem: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1

So `storageClassName: ""` is definitely not ideal per se, but might be a viable workaround for people with CSI enabled trying to deploy Z2JH on their cluster. I'm trying to figure out what were to break if storageClassName: '' were the z2jh default.

**Comment by consideRatio** [comment]
Thanks for your research work and exploration of this topic, it is a complicated one!

### Current situation

Currently, our template don't render the pvc's spec.storageClassName unless its associated helm chart value is explicitly specified to be a string (blank or non-blank).

```yaml
  {{- if typeIs "string" .Values.hub.db.pvc.storageClassName }}
  storageClassName: {{ .Values.hub.db.pvc.storageClassName | quote }}
  {{- end }}
```

Our default value for storageClassName is `nil`, meaning, storageClassName won't be rendered by the template at all. This has been the default for four years.

### Suggested change

You suggest setting our `storageClassName` value to a a blank string, making the default behavior change for anyone that hasn't explicitly specified a value of their own.

### My concerns for a change

1. Is this a breaking change for users that are not experiencing troubles at this point in time?
2. Will a new default of a blank string cause trouble down the line given the challenge of patching PVCs?
3. How confident are we about our answers to the questions above?
4. Is changing the default to be preferred over documenting how to handle issues about this - such as maybe setting a storageClassName value manually?

To reduce concerns it would be great to see other Helm chart maintainers having considered this as well, and concluded that setting it to a blank string is the way to go. In recall a lot of issues around this in many helm charts, so I'm extra cautious about changes to this setting and its complexity.

**Comment by manics** [comment]
Doesn't `storageClassName: ""` [disable dynamic volumes](https://kubernetes.io/blog/2017/03/dynamic-provisioning-and-storage-classes-kubernetes/), which means an admin would have to manually create a PV, or deliberately unset `storageClassName` to use the default dynamic provisioner?

Did you install a second dynamic provisioner causing the default provisioner to change? If so this sounds like something went wrong during the installation of the storage- I'd have thought the default shouldn't have changed.

**Comment by snickell** [comment]
Definitely appreciate quite viscerally the balance between k8s chart ripple breakage risk, and accomodating what is in 2022 very much an edge case, I'd be extremely cautious if it was me! 🤙🏽

I like documentation in general for handling edge cases like this. To be effective in this case, we'd want the error message to be very easily searchable for what is otherwise quite possibly a "where do I even start with this" long debug (it was for me).

I've been exploring other possible approaches.... what would you think of the idea of setting adding a default annotation to values.yaml for `hub.pvc.annotations` of `"helm.sh/resource-policy": keep`. This would effectively halt helm-driven changes to the `hub-db-dir` PVC (it becomes a helm created but not managed resource, and thus not modified), which seems reasonable to me given the PVC is immutable anyway, and `helm --force` no longer works properly with PVCs as of helm3 anyway, so you're not losing anything except flagging the warning (which is of value, for sure).

**Comment by snickell** [comment]
In case one version you did want to change the hub-db-dir chart, I /think (again tbd) to implement a helm hook that would do a delete and recreate of the resource (required anyway to patch it since, again, immutable and helm v3.x isn't handling `--force` correctly for immutable PVCs afaict)

**Comment by snickell** [comment]
I'm experimenting with `helm.sh/resource-policy: keep` as an approach and seeing how it behaves in different conditions, don't have a lot of hours to spend this week, but I'll advise when I know more.

**Comment by snickell** [comment]
Here's the upstream helm issue: https://github.com/helm/helm/issues/6642#issuecomment-542836520

They approached this by not setting `storageClassName: null`. Is `storageClassName: default` a standard k8s thing? Maybe that's what we should be doing instead?

Sorry, don't have more time for this this week, so not looking into this further as much as I usually would, but wanted to share the new info here anyway.

**Comment by consideRatio** [comment]
@snickell thank you for diving into this rabbit hole and sharing your findings!

So https://github.com/helm/helm/issues/6642#issuecomment-542836520 describes how they had problems when a Helm chart's template rendered a PVC resource with `storageClassName` being set to to null (`storageClassName: `), and due to that, suggests the very common practice we now apply of not rendering something unless an explicit value is provided.

Currently, we don't render the `storageClassName` unless an string value is set:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/fb963101f367010815dcf3b4ef3d6384e2e32c25/jupyterhub/templates/hub/pvc.yaml#L17-L19

My current understanding leads me to think this is unrelated to how this Helm chart renders the `storageClassName`. Instead I'm thinking that on GKE, a `StorageClass` is available by default, which is annotated as a default StorageClass - specifying storage to allocate when no specific storage type is requested. On GKE, that default StorageClass resource references that `gcp-pd` should be used to provide storage. And, that, is what seem to cause issues when the PVC is bound to the dynamically provided PV. The issue seems related to modifying `volumeName` based on what you are saying.

At the same time, it seems that setting the `volumeName` is core functionality after having been bound to a PV is common for all providers of storage given whats said in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/918#issuecomment-1032826619.

> Also note this has nothing to do with the csi driver, this is core k/k behavior.

Overall, I don't get why there is an error reported from `helm` as I figure it should be allowed to change the `volumeName` after all. I'd be curious to compare:

1. Create a PVC resource manifest without `storageClassName` or `volumeName` specified, then `kubectl apply` it and see it successfully get bound and updated to a new state where at least `volumeName` is specified.
2. Create a dummy Helm chart that only renders the fixed PVC manifest, not being influenced by any values, and do a `helm install` of that, followed by a `helm upgrade` of it. If you get a response saying "nothing has changed" or similar, add an annotation to the PVC manifest to force it to act in some way - a PVCs annotation can be updated!

---

I consider the action points related to this issue remain to dig deeper, without a clear understanding I don't dare support a configuration change that I can see go wrong in many ways.

**Comment by consideRatio** [comment]
@snickell I'll go for a close on this issue as it is not stale and I see no action points associated with it.
