### ISSUE TITLE
Replace deprecated base_url with bind_url

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#2592]
### Proposed change
This chart uses `c.JupyterHub.base_url`
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/6f4609e2f73258c7e0146f8e849d31aa7fe7f09f/jupyterhub/files/hub/jupyterhub_config.py#L83-L94
This property was deprecated in JupyterHub 0.9 (which I've only just realised!), the replacement is `c.JupyterHub.bind_url`.
https://github.com/jupyterhub/jupyterhub/blob/36cad38ddf00c3fe92d813fd7bf8715fb876d006/jupyterhub/app.py#L623-L633

### Alternative options
Do nothing

### Who would use this feature?
I think Z2JH should be an example of best practice, which means avoiding deprecated features.

### (Optional): Suggest a solution
Keep the Helm chart property `hub.baseUrl` (since it affects components outside JupyterHub), but use it to set bind_url in `jupyterhub/files/hub/jupyterhub_config.py`

**Comment by consideRatio** [comment]
I'm not sure what makes sense here because I don't confidently overview the jupyterhub configuration. While `base_url` was a prefix only, `bind_url` includes more I think, and then there is `hub_bind_url` as well etc.

I can imagine this may requires a breaking change, so it would be great to nudge this pre-2.0.0 release.

Here are some baseUrl related logic, note that its used both by the helm chart templates, and the jupyterhub_config.py file.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/31edd218ceb02d4f1220da4a6c6e41942a517926/jupyterhub/files/hub/jupyterhub_config.py#L82

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/31edd218ceb02d4f1220da4a6c6e41942a517926/jupyterhub/files/hub/jupyterhub_config.py#L95-L105

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/31edd218ceb02d4f1220da4a6c6e41942a517926/jupyterhub/files/hub/jupyterhub_config.py#L354-L356

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/31edd218ceb02d4f1220da4a6c6e41942a517926/jupyterhub/schema.yaml#L413-L418

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/31edd218ceb02d4f1220da4a6c6e41942a517926/jupyterhub/templates/ingress.yaml#L20

**Comment by manics** [comment]
https://github.com/jupyterhub/jupyterhub/pull/4564
