### ISSUE TITLE
Detailed instructions for setting up Google Auth

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#26]
A lot of people (particularly at universities) probably just wanna use Google Auth. Let's make sure there's a detailed guide for this.

**Comment by choldgraf** [comment]
Definitely agree - who knows the most about this? @ryanlovett ? you?

**Comment by ryanlovett** [comment]
Its fairly straightforward. I can add the info.

**Comment by ryanlovett** [comment]
Some info for this is in https://zero-to-jupyterhub-with-kubernetes.readthedocs.io/en/latest/extending-jupyterhub.html#authenticating-with-oauth2. Do you want the details on the "extending" page or on its own?

**Comment by choldgraf** [comment]
Browsing through that stuff, I think there's room for creating a more "user friendly" version of this documentation, since we want people who may not have any experience with this to be able to set up jupyterhubs (e.g. professors at a university). The google console oauth instructions, for example, are kind of a big wall of text. Maybe we can sit down and think about the distilled minimum-viable-product version that users might want, and then link people to the full documentation if they want more context. WDYT?

**Comment by ryanlovett** [comment]
Okay, I see what you mean. Let me work on a standalone doc for the use case you mentioned and then we can iterate on it.

**Comment by willingc** [comment]
One thing that might be nice is to have a graphical flow chart from start to finish that branches on decision points (type of auth, etc).

**Comment by choldgraf** [comment]
we'd like to have something like this for the whole jupyterhub workflow,
I'd imagine!
--

**Comment by willingc** [comment]
@choldgraf Absolutely!

**Comment by consideRatio** [comment]
Solved within: https://zero-to-jupyterhub.readthedocs.io/en/stable/authentication.html#google-oauth, this is referenced from the authentication section.
