### ISSUE TITLE
AKS says: "The request did not have a subscription or a valid tenant level resource provider" 

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#2611]
### Bug description
Instructions for setting up on Azure with autoscale do not proceed as expected, possibly due to changes in the Azure CLI/API.

#### Expected behaviour

In https://zero-to-jupyterhub.readthedocs.io/en/latest/kubernetes/microsoft/step-zero-azure-autoscale.html, the step: 

```
SP_PASSWD=$(az ad sp create-for-rbac \
    --name <SERVICE-PRINCIPAL-NAME> \
    --role Contributor \
    --scope $VNET_ID \
    --query password \
    --output tsv)
```
Should proceed without error.

#### Actual behaviour

The following response is emitted:

```
WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration
WARNING: Creating 'Contributor' role assignment under scope 'qsiprep-vnet'
WARNING:   Role assignment creation failed.

WARNING:   role assignment response headers: {'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'x-ms-failure-cause': 'gateway', 'x-ms-request-id': '99c9dc9d-ac27-44e6-8e4f-590d488c4685', 'x-ms-correlation-request-id': '99c9dc9d-ac27-44e6-8e4f-590d488c4685', 'x-ms-routing-request-id': 'WESTUS2:20220309T185210Z:99c9dc9d-ac27-44e6-8e4f-590d488c4685', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 09 Mar 2022 18:52:10 GMT', 'Content-Length': '135'}

ERROR: The request did not have a subscription or a valid tenant level resource provider.
```

**Comment by AlexChung1995** [comment]
Hi @arokem are you able to deploy new jupyterhub instances on AKS by following the documentation? I recently needed to redeploy, and have found ingress is broken for even the most basic deployment. The pods look fine otherwise though. Not sure if I'm going crazy or if other people are experiencing the same thing.

**Comment by consideRatio** [comment]
@AlexChung1995 can you elaborate how ingress is broken in more detail?

If you think the documentation is outdated, because you followed examples on how to configure the helm charts `ingress` config, and you ended up with errors - it would be great to track in a dedicated issue if you have time to describe it!
