### ISSUE TITLE
Add Gitlab to authentication docs

### ISSUE THREAD

**Issue by RaananHadar** [jupyterhub/zero-to-jupyterhub-k8s#2679]
### Proposed change
Gitlab is a relatively common provider for oauth2. I think its a common enough provider to include [it in the docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html). Currently, the authentication and authorization does not contain instructions how to set it up and i've found the scenario of setting it up either via the generic oauth provider and the GitLabOAuthenticator to be troublesome.

### Who would use this feature?
Many users use it as part of their day to day development workflow and it also offers on-prem oauth capabilities compared to public sites, making it attractive for such use cases. 

### (Optional): Suggest a solution
Creating such docs, with instructions on how to setup a private gitlab host instance would be very beneficial. If you can provide a draft of a working configuration here in the meanwhile it will also be very helpful.

**Comment by consideRatio** [comment]
While this Helm chart has examples on how to configure authentication for various providers via jupyterhub/oauthenticator, it has been shown to be unsustainable to maintain the same kind of documentation in both places. Due to that, I think we must opt to not provide examples on how to configure GitLab in this Helm chart, but provide a good general example on how to make use of any authenticator in juptyterhub/oauthenticator.

**Comment by manics** [comment]
I agree, especially since pass-through configuration means any docs would initially duplicate (and inevitably later lag behind) the existing OAuthenticator docs
