### ISSUE TITLE
Documentation for practitioners

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#278]
One thing that came out of conversations at the MSDSE summit was that while the Z2JH guide is great for setting up your own JupyterHub, there isn't a good resource for the squishier questions like *why* you'd want to use it, *how* it benefits teaching in the classroom, and *how* to use it most effectively.

I think resources like this would be really valuable to the community. I wonder if it'd be worth creating a space where this kind of information can live. I imagine it being a place where people could store their experiences, share tips (e.g. the existence of nbgitpuller), etc.  Ideally it'd be more community-driven than just maintained by the jupyterhub team.

Anyone have thoughts/ideas on something like this? A wiki? A "Zero to JupyterHub for Education" site like this one? (and similar kinds of sites if other obvious use-cases pop up)

**Comment by consideRatio** [comment]
This post successfully made me know the existence of nbgitpuller. ;D

I'd love a way to get in tough with teachers and similar who wants to educate students using JupyterHub. I'm a teacher in math / physics, my goal is to use JupyterHub and nbgrader in order to allow my students to do hand in exercises presented in Jupyter Notebooks about math. I want it to be able to scale, so that multiple schools could use the same system and get help with integrating programming with math without knowing a lot about programming themselves.

Did you know about this group by the way? https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/jupyter-education

**Comment by choldgraf** [comment]
Ah yes - I imagine this as some kind of place to codify the wisdom learned in the jupyter for education community!

**Comment by choldgraf** [comment]
do any of the pages underneath https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html#resources-from-the-community work for this? What are ways that we could modify what's there so that it's more useful?

**Comment by consideRatio** [comment]
**Actionplan:**
Create a stub where we gather wisdoms regarding usage or non-usage of a z2jh deployment for educational contexts under resources-from-the-community.

**Comment by consideRatio** [comment]
Closed and encompassed as a wish for improvement in the issue linked above.
