### ISSUE TITLE
Let `hub.db.upgrade` be True by default and reduce complexity?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2783]
In https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2779#issuecomment-1173835935 I guessed in response to @manics on why we have a quite advanced logic associated with `hub.db.upgrade` configuration, where the unset value means it is true for `sqlite` databases (default), but false for external databases.

I want to consider if we should make the system easier to communicate about etc, and simply let `hub.db.upgrade` be true by default, and remove the in-between behavior state where unset meant you would have upgrades for sqlite but not for other dbs?

The key value as I see it, is that the behavior is simpler. With simpler behavior, we can communicate easier about this, people understand it better, and that can be a win-win for users and maintainers.

@manics @yuvipanda @minrk what do you think about this?

**Comment by manics** [comment]
I think it makes sense. Sqlite is as much "production" as an external database. If we're not completely confident that the external DB schema upgrade works then we can't release Z2JH 2.0.0 regardless of this decision.

**Comment by manics** [comment]
I'm trying to add a DB upgrade test for PostgreSQL https://github.com/manics/zero-to-jupyterhub-k8s/tree/test-postgres

**Comment by minrk** [comment]
It doesn't have to do with our confidence about the schemas. All are pretty thoroughly tested in JupyterHub itself. I think it's true by default for sqlite because our own sqlite upgrade makes a backup as part of the process, so recovery should always be possible. We can't backup external databases as part of upgrade (users have to do this before upgrading jupyterhub), so a database upgrade has a better chance of being destructive _and unrecoverable_ with postgres, etc.. Because "backup, then upgrade" (what everyone should always do) necessarily requires out-of-band user actions, the potentially destructive action on requires 'confirmation' of a sort (what little we have available in helm).

That's what I recall about the reasoning behind it, anyway. I'm open to changing the default, since I suspect it is a pain and most folks probably set `hub.db.upgrade` to True as soon as they encounter this once, and then leave it for the next upgrade. I would _much_ prefer a regular "confirm you're ready to upgrade the database" prompt, if we could have one. As it is, I guess docs are all we have, but that's little help for folks who need to recover their database after an upgrade they want to roll back but can't.
