### ISSUE TITLE
Request for support of helm versions lower than 3.5

### ISSUE THREAD

**Issue by hessmjr** [jupyterhub/zero-to-jupyterhub-k8s#2835]
### Bug description

Helm chart is not backwards compatible due to use of `dig` function in [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/hub/_helpers-passwords.tpl#L35).

#### Expected behaviour

Not require Helm upgrade beyond 3.5 (currently out of my control but seems strange to require such a late version of Helm in order to utilize latest stable chart.

#### Actual behaviour

Helm throws an error when parsing values

```
Error: parse error at (jupyterhub/templates/hub/_helpers-passwords.tpl:35): function "dig" not defined
```

### How to reproduce

1. Have version of Helm before 3.5
2. Run Helm upgrade with Jupyterhub helm chart

**Comment by consideRatio** [comment]
We need the "lookup" function as well, it was introduced in 3.x sometime as well. I also recall a few bugs that make me want a somewhat modern version among all users so i know that when an issue is reported for a new version of the helm chart - i can rule out very old helm bugs.

With helm 3.9 out, and helm being a local CLI or library, it seems very reasonable to ask that users install a modern version.

Are you unable to upgrade helm because you are using a helm library pinned by other party which has been slow on updating helm, like i think argo does?

I dont want to adjust based on this input yet, but if you think a patch to stop needing helm 3.5+ can made to instead need 3.x+ by a smaller refactoring - I'd be open to consider that.

**Comment by consideRatio** [comment]
Helm 3.5.0 was released 13 Jan 2021

**Comment by manics** [comment]
There's a couple of secvulns too: https://www.cvedetails.com/vulnerability-list/vendor_id-20129/product_id-57140/year-2021/Helm-Helm.html
I don't think they're relevant to Z2JH, but they may affect other charts.

**Comment by hessmjr** [comment]
> Are you unable to upgrade helm because you are using a helm library pinned by other party which has been slow on updating helm, like i think argo does?

I am unfortunately.  For the time being I'm simply reverting to 0.11.1 as I saw another user comment due to the same constraints.

**Comment by consideRatio** [comment]
What version of argo are you using then, and can you upgrade to a more modern version of argo that use a more modern version of `helm`?

If its clear that a lot of users are stuck at helm 3.3 or 3.4, effort to supporting those could be considered - but without further information this is not a request that can be considered.

**Comment by consideRatio** [comment]
I see that argo of non-very old versions also keep up with the `helm` version, see https://github.com/argoproj/argo-cd/blame/master/hack/tool-versions.sh#L12.

**Comment by hessmjr** [comment]
Oh sorry, you said 'like'.  The way our operator is setup currently uses an older version with middleware logic I'm not entirely familiar with.  Needless to say there is a process change required to get Helm to upgrade, which I can get into progress but in the time being I wanted to point out that lower Helm support would be nice with newer chart versions.

As mentioned I figured out a workaround in the time being.

**Comment by consideRatio** [comment]
@hessmjr I'll go for a close of this issue at this point - I don't want us to revert to supporting older versions of `helm` at this point unless its very clearly motivated. Part of the motivation I think was missing was knowledge that it would be helpful to support for example 3.2, 3.3, or 3.4 _specifically_ - I know we can't support anything older than 3.2.0 because `lookup` was introduced there.
