### ISSUE TITLE
Consider removing image puller

### ISSUE THREAD

**Issue by kujon** [jupyterhub/zero-to-jupyterhub-k8s#2900]
Hello Folks 👋 

It would be great to understand the reasoning behind having dedicated pods on every node in the cluster responsible for pulling images (both in pre-install phase as well as continuous puller at all times). Is there anything it does that couldn't be handled with [image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)? At least I feel like this could be an opt-in instead of the default behaviour, for the following reasons:
- it's quite a rare approach, which in our case, significantly increased time spent debugging why the chart wasn't installing (turns out the default image tag is hardcoded to `set-by-chartpress`)
- the default behaviour pollutes the entire cluster, both with unnecessary pods, as well as unnecessary images
- added complexity to the chart.
- there are projects such as [kube-fledged](https://github.com/senthilrch/kube-fledged) which allow people to have this behaviour that is not limited to jupyterhub

**Comment by minrk** [comment]
> Is there anything it does that couldn't be handled with [image pull policy](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy)?

Yes, it's entirely unrelated to the imagePullPolicy. imagePullPolicy only has its effect when the pod is requested, which is far too late. The point is to have the image present _before_ the pod is requested. The image puller solves an important and widespread problem for jupyterhub deployments (vastly improved spawn time and spawn consistency), which is described in the kube-fledged use cases. So we shouldn't remove it, but there may be other implementations like kube-fledged that could be an awesome solution to the same problem. Thanks for pointing to it!

> At least I feel like this could be an opt-in instead of the default behaviour,

I think that's a reasonable point of view, but we see z2jh as a jupyterhub _distribution_ with a collection of good defaults. Making the usually best choice an opt-in optimization would mean that most folks who should use it (read: most folks) would have a worse experience. For advanced users, turning it off is a smaller burden than the opposite. The target audience of z2jh is perhaps not the same as most charts (z2jh is frequently the first and only thing folks have deployed on kubernetes).

> it's quite a rare approach, which in our case, significantly increased time spent debugging why the chart wasn't installing (turns out the default image tag is hardcoded to set-by-chartpress)

That suggests a quite unusual way to use the chart - rather than installing from a published chart version via `helm install` , the _development_ repo has been forked. The repo itself is a _template_ and must be built with chartpress. It might be useful to understand why this unusual approach has been taken.

**Comment by kujon** [comment]
Thanks for your prompt response!

> That suggests a quite unusual way to use the chart - rather than installing from a published chart version via helm install , the development repo has been forked. The repo itself is a template and must be built with chartpress. It might be useful to understand why this unusual approach has been taken.

That solves one mystery! While we did install the chart from https://jupyterhub.github.io/helm-chart/, what we tend to do is to copy&paste the default values for each chart and set them explicitly. That way, if we need to change any value, we've got a reference at hand. In this case, we grabbed the default values from [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml) which explains it.

> The target audience of z2jh is perhaps not the same as most charts (z2jh is frequently the first and only thing folks have deployed on kubernetes).

Even with this audience, this point could be argued either way. E.g. should jupyterhub chart go as far as installing an ingress controller if its primary target is jupyterhub-exclusive clusters?

Anyway, it's much clearer now as to why certain decisions have been taken, I'll leave it up to the maintainers to decide what to do with this issue, we managed to get it to work 😄

**Comment by kujon** [comment]
@minrk mind pointing me at the best `*.md` file to do a PR against to explain it to the new users, please?

**Comment by consideRatio** [comment]
> mind pointing me at the best *.md file/docs to do a PR against to explain this to the new users, please?

I think this is relevant documentation, but I wasn't sure what the "this" part referred to exactly: https://z2jh.jupyter.org/en/stable/administrator/optimization.html#pulling-images-before-users-arrive

Please go for a discourse.jupyter.org post for further help though!
