### ISSUE TITLE
Parameter "singleuser.defaultUrl" not working

### ISSUE THREAD

**Issue by AdrianSanchezLopez** [jupyterhub/zero-to-jupyterhub-k8s#2950]
### Bug description

With the lastest version of the Helm chart 2.0.0, the parameter "singleuser.defaultUrl" does not work. Setting it to "/lab" previously redirected the single-user servers to JupyterLab, now it opens the regular jupyter notebook

#### Expected behaviour

Redirect the user's address to /lab when setting `singleuser.defaultUrl: "/lab"`

#### Actual behaviour

It does not redirect to /lab, but instead to "/tree", the regular jupyter notebook

### How to reproduce

1. Deploy helm chart 1.2 with `singleuser.defaultUrl: "/lab"`
2. Start a User server: it gets redirected to "/lab"
3. Deploy helm chart 2.0.0 with `singleuser.defaultUrl: "/lab"`
4. Start a User server: it gets redirected to "tree"

### Your personal set up

Tested with minikube version: v1.24.0
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by consideRatio** [comment]
This can be influenced by various things in both your config and image.

1. Have you in any way changed your singleuser.image since upgrading, or can we assume its unrelated to the image?
2. What does your `singleuser.cmd` specify?

Overall, this is a very tricky configuration, and we've dwelled on how to make things work well in https://github.com/jupyterhub/kubespawner/issues/493#issue-826161387. I think there may be a quickfix of making sure that you have `singleuser.cmd` set to something, such as the default value of the Helm chart. In other words, to not override that with a falsy value.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/56aeae2810c8f4f21e709bc68eabd0a4ef2f52fa/jupyterhub/values.yaml#L400

**Comment by AdrianSanchezLopez** [comment]
Hi, thank you very much for your answer, problem found and solved! 
I did changed the singleuser.image and updated it, but it wasn't a dockerfile based on the latest 'jupyter/base-notebook' compatible with hub:3.0.0. Now with the updated singleuser image everything works as expected.
Thanks for the quick response!
