### ISSUE TITLE
413 request entity too large with Ingress proxy

### ISSUE THREAD

**Issue by WhiteCat6142** [jupyterhub/zero-to-jupyterhub-k8s#3274]
### Bug description

Using ingress mode, I got 413 when I save a file (not so large).
I found that wrong ingress proxy configuration causes this problem.

** I already found a solution but I think it should be reported and fixed***

https://z2jh.jupyter.org/en/latest/administrator/advanced.html

https://stackoverflow.com/questions/64759983/nginx-ingress-returns-413-entity-too-large

### How to reproduce

1. Launch JupyterHub for Kubernetes with ingress.
2. Go to pages
3. Save a file

#### Expected behaviour

Saved a file successfully.

#### Actual behaviour

Got 413 request entity too large with Ingress proxy.

### Your personal set up

 - OS:
ubuntu 20.20
- Kubernetes:
microk8s: v1.26.11
 - Version(s):
JupyterHub with Kubernetes: 3.0.3
Jupyterlab: 4.0.8

#### Solution

Change JupyterHub Ingress configuration.

```jupyterhub.yaml(partial)
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jupyterhub
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "700m"
```

**Comment by manics** [comment]
Hi! This has to be configured by the JupyterHub/K8s admin. We can't make it a default in Z2JH because there are multiple ingress providers, the parameter could by set by the K8s admin and we wouldn't want to hard-code an override, and it depends on what you as the JupyterHub admin want to set as the maximum size.

If you think the docs could be improved though please open a pull request. Thanks!
