### ISSUE TITLE
Add section on backups

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#332]
We should include a section on best-practices for backups in the z2jh guide.

**Comment by tracek** [comment]
The would be very much appreciated. I am now trying to figure it out myself, this would be a real time-saver.

**Comment by consideRatio** [comment]
Related to backup in the sense of ensuring stability of the hub-db-dir or any user volume.

The Helm chart has has through a PVC and the not-in-chart default StorageClass created the hub-db-dir volume. This should preferably have the reclaimPolicy of retain instead of delete as decided by the storageClass created by the cloud provided.

We could create our own storage classes but that has downsides as the storage class is quite cloud specific. We could also patch the storage class, but it would influence behavior in other namespaces... We could also patch the hub-db-dir PV directly or also all users PV's.

### Patching PVs
https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/#why-change-reclaim-policy-of-a-persistentvolume

### About storage classes
https://kubernetes.io/docs/concepts/storage/storage-classes/

# A note on labels for PVCs and PVs
I'm not sure when, but in a kubespawner PR i introduced some labeling, adding the ability to label PVCs and associated PVs `hub.jupyter.org/storage-kind: user` through some traitlet. Along with this, I also ensured that all new user PVCs got this label and that the hub-db-dir PVC got a similar label but with the value of `core`.

**Comment by consideRatio** [comment]
I've added details about how to ensure PVs are not deleted if a PVC is deleted, for example by deleting the entire namespace or cluster, but instead being kept in `retain`.

Closing this in favor of #901 for now.
