### ISSUE TITLE
Does it support Single Sign One?

### ISSUE THREAD

**Issue by chominnn** [jupyterhub/zero-to-jupyterhub-k8s#3483]
I want to configure SSO using Keycloak and I wonder if you support it

**Comment by consideRatio** [comment]
Its possible by using the GenericOAuthenticator, see the documentation from the jupyterhub/oauthenticator project. See for example https://oauthenticator.readthedocs.io/en/latest/tutorials/provider-specific-setup/providers/generic.html.

There is an issue in https://github.com/jupyterhub/oauthenticator/issues/107 related to this, because we doesn't have docs on use with keycloak specifically yet. I've set it up historically successfully though.

Note that this is a support like question, so they should ideally be raised at discourse.jupyter.org.

**Comment by chominnn** [comment]
@consideRatio 

I'm sorry I'm not used to github.
Thank you for your response.

**Comment by consideRatio** [comment]
No worries @chominnn!! Good luck!
