### ISSUE TITLE
Jupyterhub on Digital Ocean

### ISSUE THREAD

**Issue by ZachGlassman** [jupyterhub/zero-to-jupyterhub-k8s#401]
I'd like to document the process for deploying Jupyterhub on Digital Ocean.  I'm thinking mostly in terms of altering the guide and adding a section for Digital Ocean (analogous to https://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/create-k8s-cluster.html#google-cloud). 

Thoughts?

**Comment by choldgraf** [comment]
+1 to the idea. Once Kubernetes is set up then the rest of the JHub workflow is pretty similar on all of the cloud platforms.

Could you give a link (or some simple/actionable steps) to setting up k8s on digital ocean? The workflow we've used is to begin with these steps, then I'll give a shot at setting it up, create a draft of the additional instructions, and then we can iterate on that a bit before making a PR to z2jh.

I'm happy to give this a shot either later today or next week! (or if somebody else wants to give a shot they can go for it as well!)

Also of note - is there a way to get some free credits on DO so that we can try this out without spending a bunch of money?

**Comment by ZachGlassman** [comment]
You might start here:

https://github.com/janakiramm/do-k8s

**Comment by choldgraf** [comment]
gotcha - thanks for those links. That's a bit more involved than I was expecting...it looks like you basically need to set up kubernetes from scratch yeah? (as opposed to DO having "special" support for kubernetes a-la google/aws/microsoft)

**Comment by ZachGlassman** [comment]
Yeah I have been setting it up from scratch.  I think its more in line with the open stack issues than with google/aws/microsoft.

**Comment by willingc** [comment]
@ZachGlassman @choldgraf I think that writing a Digital Ocean specific tutorial to host on the Digital Ocean site would be great Zach. Please let us know if you do so and we can link to it. Alternatively, please feel free to add it to the [Zero to JupyterHub wiki](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/wiki) under resources.

Closing this issue as too involved for the basic zero to jupyterhub guide.
