### ISSUE TITLE
Improve the "how to prepare your Dockerfile" section

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#484]
Hit three main use-cases:
 * Option 1: Use jupyter-dockerstacks as a pre-existing image
 * Option 2: Creating your own Dockerfile from scratch
 * Option 3: Use repo2docker

---

**Current in 0.7.0:**
- [x] Selection of jupyter/docker-stacks
- [x] Extension of jupyter/docker-stacks

**Comment by consideRatio** [comment]
I restructured this section for jupytercon2018, many started using repo2docker and failing since for different reasons and unmet expectations on the outcome.

**The current docs have:**
1. Choosing an image from docker-stacks
2. Extending such image

**I'm open for the update of:**
3. Short note about building one from scratch and known but perhaps not exhaustive requirements on the Dockerfile. (jupyterhub package, the startup command, uid, more?)

---

This means that we currently no longer provide a repo2docker suggested path to get a suitable z2jh image. I found that it was a lot more complicated and led to complications with storage etc as compared to the docker-stack options. This led to the opinion that repo2docker shouldn't be suggested as an option within z2jh to build user images.

**Comment by consideRatio** [comment]
Yepp I think so =/

**Comment by consideRatio** [comment]
I'm closing this as we have "Choose and use an existing Docker image" and "Customize an existing Docker image", I feel this is sufficient for now without explicit user requests for more. See: https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-environment.html
