### ISSUE TITLE
JupyterCon talk about z2jh [CFP end March 6]

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#492]
I think we should also have a talk specifically about z2jh (rather than JupyterHub in general - although maybe not?). Would include some history of the project, performance measures, quick demos and 'where we are going'.

Could also be finally an opportunity to replicate the Kelsey Hightower style 'Ok Google, deploy a JupyterHub for me' demo :)

**Comment by yuvipanda** [comment]
@consideRatio would you like to be involved in giving the tutorial? I think you've spent a lot of time digging through the code from a fresh perspective, and it would be great to have new faces in there!

**Comment by consideRatio** [comment]
@yuvipanda wow big decision for me but I know the pros outweighs the cons already. It would simply be too fun, too meaningful, too exciting, too potentially life changing to say anything other than yes to such opportunity!

Yes! I'd love to be involved! I'll solve potential hurdles and make it happen!

Woooow I'll be going to JupyterCon! It was a while since I felt such childlike excitement! :D
![excited-cat](https://user-images.githubusercontent.com/3837114/36006205-d651495c-0d3b-11e8-9b73-5617e973fe65.jpg)

By the way, no matter what, this will be an awesome experience for me, so please don't feel any pressure for involving me!

**Comment by choldgraf** [comment]
this post warms my ❤️

**Comment by willingc** [comment]
Just a reminder CFP closes March 6.

**Comment by choldgraf** [comment]
shall we close this now that it's submitted? Or leave open for discussion in the future if it's accepted?

**Comment by willingc** [comment]
Let's close. If the talk is accepted, we can open a new issue referring to this one ;-)
