### ISSUE TITLE
Group ID of jovyan in singleuser image

### ISSUE THREAD

**Issue by betatim** [jupyterhub/zero-to-jupyterhub-k8s#506]
Should the group ID used by jovyan in the singleuser image be 1000 or 100?

[Here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/76fcf7b208d19593ff5ce536a8319f6a3400e714/jupyterhub/values.yaml#L131) it is set to 1000 but in the base image that the singleuser image is based on jovyan is in group 100.

I think this is a typo.

**Comment by consideRatio** [comment]
I worked around this feeling bad about it... I modified my singleuser image to add a name for the group 1000 to avoid showing my students that error message when they open up a terminal.

As one can see from the base-notebook image, used by all the images in the jupyter docker-stack, they use the group ID of 100 rather than 1000.
https://github.com/jupyter/docker-stacks/blob/92fe05d1e7e5ec1f8e804c8a80560fc5d7b4efa0/base-notebook/Dockerfile#L35-L50

**Comment by consideRatio** [comment]
Hmmmm, will a change to 100 cause permission issues on the storage?
