### ISSUE TITLE
Modifying configmaps + manifests not defined by us

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#530]
# Modifying pre-existing k8s resources
I'd like for the guide to allow for simple setup of something awesome. But some thing I realize we might need the user to do seem a bit much. Can we make it even simpler?

### Situation 1
Say for example that we want to set the `preventSinglePointFailure` to `false` within the configmap named `kube-dns-autoscaler` that isn't defined by us.

__Can we...__
- [x] Do this with `kubectl edit` command
- [ ] Do this with a one liner
- [ ] Do this by having a `.yaml` file somewhere

```
kubectl edit configmap kube-dns-autoscaler --namespace=kube-system
```

### Situation 2
Say that we want to delete the kubernetes dashboard, it seems like it will reappear whenever make a new helm upgrade even though we delete the deployment. To avoid this, we must delete a manifest on the kubernetes master node it seems. See #529 for details.

__Can we...__
- [ ] Do this by ssh-ing to master node and running `rm` etc?
- [ ] Do this with a one liner
- [ ] Do this by having a `.yaml` file somewhere

**Comment by yuvipanda** [comment]
hmm, I think we need a place for such information, but not directly in the guide? Since modifying those things has lots of other consequences than just for the hub. For example, preventSinglePointFailure to false might cause DNS to not work for several minutes sometimes - this means no outgoing network connections from inside pods for several minutes, since all DNS lookups will fail! This seems unideal...

The other problem here is that some things at the cluster level are intensely dependent on how it was set up, and what is perfect in one situation can be catastrophic in another. For example, on GKE you can't really 'ssh' into a master. On clusters set up with `kubeadm`, you can - but you might have inintended consequences based on which files you delete. On clusters set up with `acs-engine`, you can ssh into master too - but I've no idea what'll happen if you touch any kube files :D 

my general preference for these kubernetes specific things that are sortof not directly tied into the hub is to have them exist in kubernetes docs or as blog posts or something, and we can link to it... But this seems unideal, and maybe we need a wiki style space for these kinda tricks?

**Comment by consideRatio** [comment]
Ah I learned so much of relevance to me by that comment @yuvipanda =D I agree with your preference!

In the future I figure we might want to have a section about cluster autoscaling in the guide, and then i figured it would be relevant to have a proposed plan on how to handle downscaling to 1 node which is not always so easy because of pods like kube-dns and spreading of hub and proxy.

Thank you for helping me out understanding these things!

**Comment by willingc** [comment]
One of the things that we have done in the past with JupyterHub is to use the GitHub wiki for the repo to document things such as discussed here. Let's use [the wiki on this repo](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/wiki) for a similar purpose. I've started the wiki homepage. Going to close this issue.
