### ISSUE TITLE
Dynamic account whitelisting

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#607]
I'm planning on hosting a jupyterhub with google authentication for a wide audience, but still retain some control of who that should be allowed to use it to save resources.

It would be great if I could...
* allow people to access the hub directly without waiting for me to whitelist them in `values.yaml` manually at the same time I don't want everybody with a google account to be allowed access.
* send personal invite links, allowing for one account to be whitelisted. "if you have this link, you can sign up for access".
* send non-personal invite links, allowing for anyone with it to setup a google account

Anyone with suggestions on how to go about this?

**Comment by danielmaitre** [comment]
Hi @consideRatio, this doesn't exactly fit what you said but would you consider using LDAP authentication instead of google? For an event where I needed to give access to a jupyter server to people I didn't know beforehand I used a LDAP I pre-populated with many EVENT01,EVENT02,... accounts with PWD01, PWD02,... passwords. All participants were sitting in the same room so it was easy for me to assign them an account.

Would something like this be feasible for you?

**Comment by consideRatio** [comment]
@danielmaitre ah! Thanks for considering this! That could make a lot of sense for having a workshop or similar!

The accounts must be their personal google accounts sadly.

**Comment by yuvipanda** [comment]
@consideRatio Google Groups perhaps? You can provide access based on membership in a google group, and use that to manage access.

I think this should be a feature / issue in http://github.com/jupyterhub/oauthenticator though.

**Comment by consideRatio** [comment]
@yuvipanda ooooh clever!
