### ISSUE TITLE
Clarify and document (if needed) image size guidelines

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#63]
The pre-puller has a timeout that is triggered for large images from dockerhub (5-6G seems to be too much). Either increase the timeout or document this.

**Comment by consideRatio** [comment]
Typical big `docker-stacks` images are ~2GB, which would pull fine on most clouds with the current 5 minute timeout (300 seconds). We should either document a recommendation of 900 second for large images or simply make it the default.

I don't think we can make the pre-puller timeout, it is the client side helm command that times out and that is not in our control.

ACTIONPLAN:
* We must document a recommendation, somewhere suitable, to use a 900 second timeout instead of the default 300 seconds, for images sized to about 6GB.

**Comment by consideRatio** [comment]
> The pre-puller has a timeout that is triggered for large images from dockerhub (5-6G seems to be too much). Either increase the timeout or document this.

There is no such issues any more, but `helm` can timeout. This is documented already though.

>    **NOTE**: With this enabled your `helm upgrade` will take a long time if you
>    introduce a new image as it will wait for the pulling to complete. We
>    recommend that you add `--timeout 10m0s` or similar to your `helm upgrade`
>    command to give it enough time.
