### ISSUE TITLE
Exposing another port in singleuser notebook

### ISSUE THREAD

**Issue by kalugny** [jupyterhub/zero-to-jupyterhub-k8s#740]
I want to have `RStudio Server` exposed on the singleuser container.
I've figured out how to use the proxy API to add the new route, but I still need the Pod to expose an additional port.

I've tried adding
```
c.KubeSpawner.extra_container_config = {'ports': [{'containerPort': 8787, 'name': 'rstudio-port', 'protocol': 'TCP'}]}
```
to `hub.extraConfig` in `config.yaml` but that didn't do the trick.

Is there a way to do this using configuration?
Thanks!

**Comment by kalugny** [comment]
OK, after _a lot_ of trial and error I found out it's `singleuser_extra_container_config`. D'oh!

**Comment by consideRatio** [comment]
@kalugny I think the `singleuser_` prefix is deprecated and was the old variant of the same thing, this is taken from fresh kubespawner source code.

![image](https://user-images.githubusercontent.com/3837114/41985134-c3367978-7a32-11e8-84f8-648506317299.png)

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/41985350-5ff44cfe-7a33-11e8-8cfb-2e5baf36d7dc.png)

**Comment by kalugny** [comment]
But the regular one didn't work for me...

**Comment by consideRatio** [comment]
Yepp I'm also confused !

**Comment by consideRatio** [comment]
@kalugny okay... thanks for posting about this issue because wow it took a lot of time for me to get 10/10 things right with this being 1 - without you considering this I'd be sitting eight hours more I figure...

I get it now, and I'll fix it. We ran into the issue of having the zero-to-jupyterhub-k8s chart setting the deprecated version `singleuser_extra_pod_config`, but if we added something to `extra_pod_config` that would get removed because an overwrite made by kubespawner seen in images above.

If I'll now go ahead and update the z2jh chart to use the new version, everybody using the new version will be fine, and those using the old will overwrite the new stuff that they previously did not overwrite...

Opening issue to discuss what to do, because it doesnt seem obvious that it is safe to switch to the new version.

**Comment by rapidnitin** [comment]
@kalugny You mentioned above that you have figured out `how to use the proxy API to add the new route`. Can you please help me with the same. I tried hub rest API but that doesn't work for adding route. I am only able to get routes only. Thanks in advance!

**Comment by kalugny** [comment]
I'm sorry, but this was 5 years ago. I don't remember and I don't even know
if it would still work 😓
