### ISSUE TITLE
pdb and hub upgrade failures

### ISSUE THREAD

**Issue by clkao** [jupyterhub/zero-to-jupyterhub-k8s#754]
It seems `helm upgrade` no longer works for latest z2jh default install, as the default sqlite-pvc is mounted by the old hub rs during upgrades, so the new pod can not mount the pv.

**Comment by consideRatio** [comment]
@clkao hmmm, so the new hub is stuck in pending because of the volume mount being occupied?

**Comment by clkao** [comment]
Back when we were using extensions/v1beta1 for Deployment, the maxUnavailable is 1, so it worked.  After switching to apps/v1beta2 the default becomes 25%, so even if we disable pdb by default, upgrading will still hang.

I think (for values.yaml) we should probably disable pdb for hub and make its strategy Recreate by default, and point people to some proper HA doc that comes out of https://github.com/jupyterhub/jupyterhub/issues/1932.

**Comment by consideRatio** [comment]
@clkao Do you recall if there is one option that would allow you to have two hubs running and make a Service nice rolling update. The mounted sqlite volume mount does not allow it, but if it is switched out to PostgreSql or similar it would work to have a rolling update right?

__Questions__
- Why haven't I experiences troubles with this?
- We could set `minAvailable: 1` with a external DB that isnt mounted, and `maxUnavailable: 1` when we have a db through a mounted volume - makes sense? I figured something like that was already configured...

We have the option of using StatefulSet instead of a Deployment as well btw, would accomplish the same thing as setting the strategy to Recreate. I'm recalling there was a potential benefit to doing that, but I have forgotten.

**Comment by clkao** [comment]
@consideRatio right, minAvailable=0 would make pg-backed hub roll nicely. kubeflow does use statefulset for hub.

re: not experienced this before: a84ad294 changed the api version for our use of deployment, so the default behaviour changed. `maxUnavailable` has since been 25% rather than 1.

**Comment by consideRatio** [comment]
@clkao 
This is my hub PDB from the cluster (I run `pdb.enabled: true`) on latest z2jh (actually ahead, with `apps/v1` on the hub deployment).

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: 2018-07-08T18:32:51Z
  generation: 1
  labels:
    app: jupyterhub
    chart: jupyterhub-v0.7-dev
    component: hub
    heritage: Tiller
    release: prod
  name: hub
  namespace: prod
  resourceVersion: "2093138"
  selfLink: /apis/policy/v1beta1/namespaces/prod/poddisruptionbudgets/hub
  uid: 52133b44-82dd-11e8-814f-42010a9c00c5
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: jupyterhub
      component: hub
      release: prod
status:
  currentHealthy: 1
  desiredHealthy: 1
  disruptedPods: null
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
```

Note that if I would update and add `maxUnavailable: 1` to the PDB as well, I get...
```
minAvailable and maxUnavailable cannot be both set
```

Hmm... For reference `maxUnavailable: 25%` will round downwards to 0.

**Comment by consideRatio** [comment]
What k8s and helm version are you using?

**Comment by betatim** [comment]
#757 is a duplicate or at least a related item to this.
