### ISSUE TITLE
v0.7 Docs - reference_docs.rst

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#802]
[The page about reference documentation](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/reference-docs.rst) is outdated, and I'm going through all the documentation in order to have a fresh update before JupyterCon 2018.

@jzf2101 @willingc @betatim @minrk @choldgraf, what would you say should be included? Perhaps we could link to some talks and workshop materials as well? Could you help me link some?

### Ideas of content for the page
- JupyterHub docs
- Littelest JupyterHub docs
- BinderHub docs
- JupyterLab docs
- JupyterCon 2018 workshop stuff

**Comment by betatim** [comment]
I'd link to the three docs you mention and then the latest Zero2JupyterHub tutorial (slides).

**Comment by choldgraf** [comment]
the challenge with slides is that they're always changing and there's no "master" copy. I think we could say "here's a reasonably up-to-date set of google slides" or something like this.

Also, we should mention "The Littlest JupyterHub" as well, since some users may *not* want the scalability of kubernetes.

**Comment by consideRatio** [comment]
Thanks!!
