### ISSUE TITLE
Add ansible play to setup jupyterhub to community resources

### ISSUE THREAD

**Issue by jmatuskey** [jupyterhub/zero-to-jupyterhub-k8s#985]
Happy to iterate with you and add anything that you think needs to be added, I've created a README that I hope is comprehensive enough.

https://github.com/spacetelescope/z2jh-aws-ansible

Ansible plays intended to set up a Jupyterhub instance from scratch. z2jh.yml tracks very closely with the AWS [zero-to-jupyterhub readthedocs](https://zero-to-jupyterhub.readthedocs.io/en/stable/) and idempotently sets up a Jupyterhub cluster. teardown.yml undoes up to a given level of the total installation, governed by which tags you specify. The default will only remove the Jupyterhub release

**Comment by consideRatio** [comment]
Hi @jmatuskey! I'm very late to respond to this issue sadly and note that it was quite a while since this ansible playbook was developed. From experience with maintaining this repository I know there have been plenty of changes in how cloud providers CLIs work etc, so at this point I'm hesitant to suggest we add your work as a suggested reference for others as it probably is outdated. What do you think?

I'll close this one as its soon two years old, sorry you didn't get a reply sooner, feel free to open a new issue with regards to contributing a resource to the z2jh.jupyter.org documentation that you think can be helpful for others to use.
