### ISSUE TITLE
Move this documentation to the `helm chart` repo

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#99]
@yuvipanda and I were discussing that it might make sense for this documentation to live in the `helm-chart` repository.

The public-facing links should all stay the same, since z2jh / zero to jupyterhub is much better than "helm chart" as a user-facing name. However, the helm chart is tightly-linked to the guide in this repo, and it would be much simpler if we could just update both the docs and the helm chart in the same PR instead of needing to update two separate repositories. The other benefit would be that we can link z2jh doc releases against the helm chart releases more easily.

Since 0.4 of the helm chart just came out, what if we merged this documentation into the helm-chart repo and updated it for 0.4, then deprecated this repository and directed people to the new location documentation? Maybe @willingc and @minrk have thoughts?

**Comment by willingc** [comment]
I'm a bit neutral on moving this since:

- the repo and the docs were pretty well publicized at the PyCon poster session
- I view the helm chart as an element/tool of future JupyterHub with Kubernetes deployments

That said, I may be missing some context that you discussed so please let me know.

I'm also looking at this as part of a longer term documentation strategy for JupyterHub where the existing JupyterHub docs are reworked as reference documentation for JupyterHub. 

I'm not against a move just trying to understand in terms of the big picture.

**Comment by yuvipanda** [comment]
We wouldn't change the docs in any fashion (I am guessing we can keep RTD to keep the URL).

This repository is 100% just user documentation for the helm-chart. Changes in the helm chart require changes here, and the documentation and the chart are versioned together. That's the core reason I want to merge the repositories. 

1. We can make sure that making a change to the helm-chart requires updating the docs. This makes it *much* harder for them to go out of date.
2. When we make releases, the docs + the chart get tagged together. This makes it much easier for people who are using an old version of the chart  to find the docs that matter to them (RTD has good support for this). 
3. I was writing the 'Contributors' section of the helm-chart repo for the release and realized @choldgraf won't make that list, since he hasn't done much work in the helm-chart repo itself (though he has contributed a lot to development of the chart!). We could obviously write tools to fix this, but I think keeping them in the same place will make this easier too.

Personally, it'll be easier for me to keep the docs up to date if they're in the same repo - I can just institute a 'whenever you add a feature or change something, you need to add a CHANGELOG entry and update the docs' rule. We can enforce this in the future for other contributors too, so we make sure that our documentation stays top notch. Documentation should stay close to the thing it is documenting, and IMO this is documenting the helm chart and so should stay together. 

We can do a proper git merge of the two trees so we won't lose any history, and add a big bold README (only) here that redirects people to helm-chart.

**Comment by yuvipanda** [comment]
I've created this PR https://github.com/jupyterhub/helm-chart/pull/39. @willingc let me know what you think!

**Comment by willingc** [comment]
I think that these docs have more than just the helm chart content and will have more over time with estimating costs, scaling, etc. which will likely have more tools than just the helm chart. It feels backwards to me to have this in the helm chart repo. It makes more sense to me have the helm chart be a part of this repo ( though I know it is easier to move the docs.

I want to think on this over the weekend. I want to give some more thought on the overall JupyterHub doc strategy. 

If you want to release 0.4 please do. The docs don't have to be versioned at the same exact time. Overall, I don't want to rush the doc move and a few extra days for us to think and discuss the broader doc plan is time well spent.

**Comment by yuvipanda** [comment]
Yes totally :)

**Comment by yuvipanda** [comment]
Yes totally :) No rush at all!

**Comment by yuvipanda** [comment]
In hindsight, I realize that we didn't frame this right. This issue is framed as a 'we have this solution, these are the problems it solves' rather than 'these are the problems we want to solve, what might the solution be'. I'm going to close this, and re-open it as a bunch of different issues that are framed the other way.

#100 is first one!

**Comment by yuvipanda** [comment]
#100, #101 and #102 are a better framing of this I think. Am going to close this one so we can continue the conversation in those three tickets.
